spring:
  application:
    name: justificacionproyectos
  main:
    allow-bean-definition-overriding: true
  jmx:
    enabled: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
  jpa:
    open-in-view: true
#    database-platform: org.hibernate.dialect.Oracle10gDialect
    #Mostrar SQL queries que se realizan
    show-sql: true 
    #Actualiza la base de datos y crea la entidad
    #hibernate.ddl-auto: update
    #generate optimization hibernate SQL
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  data:
    rest:
      base-path: /api
  thymeleaf:
    cache: false
    mode: HTML
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp-relay.gmail.com
    port: 587
    username: otri@uc3m.es
    password: ${mail.pass}
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true
# apidocencia:
  # clientid: ${justificacionproyectos.clientId}
  # clientsecret: ${justificacionproyectos.clientSecret}
  # uriauth: ${justificacionproyectos.uriAuth}
  # uriexpedientecompleto: ${justificacionproyectos.uriExpedienteCompleto}
logging:
  file:
    name: ${uc3m.logsdir}/justificacionproyectos/justificacionproyectos.log
  pattern:
    level: '%5p [${spring.zipkin.service.name:${spring.application.name:-}},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}] [%X{USER}|%X{IP}|%X{SESSION_ID}] [%X{METHOD} -> %X{PATH}]'
  level:
    org.springframework.web: ERROR
    es.uc3m: INFO
server:
  error:
    whitelabel:
      enabled: false
---
spring:
  profiles: local
  datasource:
    #driverClassName: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/justificacionproyectos?useUnicode=true&characterEncoding=UTF-8&useSLL=false&serverTimezone=UTC&useLegacyDateTimeCode=false
    username: developer
    password: ${spring.datasource.password}
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  thymeleaf:
    prefix: file:src/main/resources/templates/
  jpa:
    properties.hibernate.format_sql: true
  mail:
    host: smtp.uc3m.es
    port: 25
server:
  servlet.context-path: "/justificacionproyectos"
  port: 8080
  tomcat:
    compression: on
    compressableMimeTypes: application/json,application/xml,text/html,text/xml,text/plain

logging:
  level:
    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.web: ERROR
    es.uc3m: DEBUG
---
spring:
  profiles: dev
  datasource:
    jndi-name: "java:comp/env/jdbc/justificacionproyectos"

logging:
  level:
    org.springframework.web: ERROR
    es.uc3m: DEBUG
---
spring:
  profiles: prod
  datasource:
    jndi-name: "java:comp/env/jdbc/justificacionproyectos"

logging:
  level:
    org.springframework.web: ERROR
    es.uc3m: INFO
