---------------------- MYSQL ------------------------
CREATE TABLE TB_UC3M_INV_JUST_FICHEROS_AGR (
  NUMIDFICHEROAGR		INT		NOT NULL AUTO_INCREMENT COMMENT 'Identificador del fichero generado en el lanzamiento de la agrupación.',
  NUMIDAGRUPACION		INT		NOT NULL COMMENT 'Identificador de la agrupación de proyectos.',
  NUMIDFICHERO	    INT   NOT NULL COMMENT 'Identificador del fichero asociado.',
  PRIMARY KEY (NUMIDFICHEROAGR),
  UNIQUE INDEX PROYECTOSJUST_UK (NUMIDAGRUPACION, NUMIDFICHERO),
  FOREIGN KEY JUST_FICAGR_AGR_FK (NUMIDAGRUPACION) REFERENCES TB_UC3M_INV_JUST_AGRUPACION (NUMIDAGRUPACION),
  FOREIGN KEY JUST_FICAGR_FIC_FK (NUMIDFICHERO) REFERENCES TB_UC3M_INV_JUST_FICHEROS (NUMIDFICHERO)
) COMMENT 'Tabla que contiene la relación de ficheros generados en el lanzamiento de una agrupación.';
---------------------- ORACLE ------------------------
CREATE SEQUENCE TECNICOS_INV.JUST_FICHEROSAGR_SQ;

CREATE TABLE TECNICOS_INV.TB_UC3M_INV_JUST_FICHEROS_AGR (
  NUMIDFICHEROAGR NUMBER(8) NOT NULL,
  NUMIDAGRUPACION NUMBER(8) NOT NULL,
  NUMIDFICHERO    NUMBER(8) NOT NULL
);

COMMENT ON TABLE TECNICOS_INV.TB_UC3M_INV_JUST_FICHEROS_AGR IS 'Tabla que contiene la relación de ficheros generados en el lanzamiento de una agrupación.';
COMMENT ON COLUMN TECNICOS_INV.TB_UC3M_INV_JUST_FICHEROS_AGR.NUMIDFICHEROAGR IS 'Identificador del fichero generado en el lanzamiento de la agrupación.';
COMMENT ON COLUMN TECNICOS_INV.TB_UC3M_INV_JUST_FICHEROS_AGR.NUMIDAGRUPACION IS 'Identificador de la agrupación de proyectos.';
COMMENT ON COLUMN TECNICOS_INV.TB_UC3M_INV_JUST_FICHEROS_AGR.NUMIDFICHERO IS 'Identificador del fichero asociado.';

CREATE UNIQUE INDEX TECNICOS_INV.JUST_FICHEROSAGR_PK_I ON TECNICOS_INV.TB_UC3M_INV_JUST_FICHEROS_AGR (NUMIDFICHEROAGR);
CREATE UNIQUE INDEX TECNICOS_INV.JUST_FICHEROSAGR_UK_I ON TECNICOS_INV.TB_UC3M_INV_JUST_FICHEROS_AGR (NUMIDAGRUPACION, NUMIDFICHERO);
CREATE INDEX TECNICOS_INV.JUST_FICHEROSAGR_AGR_FK_I ON TECNICOS_INV.TB_UC3M_INV_JUST_FICHEROS_AGR (NUMIDAGRUPACION);
CREATE INDEX TECNICOS_INV.JUST_FICHEROSAGR_FIC_FK_I ON TECNICOS_INV.TB_UC3M_INV_JUST_FICHEROS_AGR (NUMIDFICHERO);

ALTER TABLE TECNICOS_INV.TB_UC3M_INV_JUST_FICHEROS_AGR ADD (
  CONSTRAINT JUST_FICHEROSAGR_PK
  PRIMARY KEY (NUMIDFICHEROAGR)
  USING INDEX TECNICOS_INV.JUST_FICHEROSAGR_PK_I
  ENABLE VALIDATE,
  CONSTRAINT JUST_FICHEROSAGR_UK
  UNIQUE (NUMIDAGRUPACION, NUMIDFICHERO)
  USING INDEX TECNICOS_INV.JUST_FICHEROSAGR_UK_I
  ENABLE VALIDATE,
  CONSTRAINT JUST_FICHEROSAGR_AGR_FK
  FOREIGN KEY (NUMIDAGRUPACION) REFERENCES TECNICOS_INV.TB_UC3M_INV_JUST_AGRUPACION (NUMIDAGRUPACION)
  ENABLE VALIDATE,
  CONSTRAINT JUST_FICHEROSAGR_FIC_FK
  FOREIGN KEY (NUMIDFICHERO) REFERENCES TECNICOS_INV.TB_UC3M_INV_JUST_FICHEROS (NUMIDFICHERO)
  ENABLE VALIDATE
);

CREATE OR REPLACE TRIGGER TG_JUST_FICHEROSAGR_SQ
  BEFORE INSERT 
  ON TB_UC3M_INV_JUST_FICHEROS_AGR FOR EACH ROW
BEGIN
  IF :new.NUMIDFICHEROAGR IS NULL THEN
    SELECT JUST_FICHEROSAGR_SQ.nextval INTO :new.NUMIDFICHEROAGR FROM DUAL;
  END IF;
END;
/
------------------------------------------------------
