---------------------- MYSQL ------------------------
CREATE TABLE TB_UC3M_INV_JUST_CONC_ENTIDAD (
  NUMIDCONCEPTOENTIDAD  INT				    NOT NULL AUTO_INCREMENT COMMENT 'Identificador interno del código de la entidad para la ayuda',	
  STRCTPCON             VARCHAR(2)    NOT NULL COMMENT 'Valor del campo CTPCON del concepto de la entidad según documento de ayuda',
  STRCTPSCO             VARCHAR(2)    NOT NULL COMMENT 'Valor del campo CTPSCO del concepto de la entidad según documento de ayuda',
  NUMIDTIPO             INT				    NOT NULL COMMENT 'Identificador del tipo de ayuda según el documento',
  STRTIPOGASTOMIN       VARCHAR(2000) NOT NULL COMMENT 'Descripción del tipo de gasto según documento de ayuda',
  NUMIDTECNICA          INT				    NULL COMMENT 'Identificador del tipo de gasto de la justificación técnica',
  PRIMARY KEY (NUMIDCONCEPTOENTIDAD),
  FOREIGN KEY JUST_CONCENTIDAD_TEC_FK (NUMIDTECNICA) REFERENCES TB_UC3M_INV_JUST_TECNICA (NUMIDTECNICA),
  FOREIGN KEY JUST_CONCENTIDAD_TIPO_FK (NUMIDTIPO) REFERENCES TB_UC3M_INV_JUST_TIPOS (NUMIDTIPO)
) COMMENT 'Tabla que contiene los valores CTPCON y CTPSCO de cada concepto de la entidad financiadora para los distintos tipos de proyecto';
---------------------- ORACLE ------------------------
CREATE SEQUENCE TECNICOS_INV.JUST_CONCENTIDAD_SQ;

CREATE TABLE TECNICOS_INV.TB_UC3M_INV_JUST_CONC_ENTIDAD (
  NUMIDCONCEPTOENTIDAD  NUMBER(8)       NOT NULL,
  STRCTPCON             VARCHAR2(2)     NOT NULL,
  STRCTPSCO             VARCHAR2(2)     NOT NULL,
  NUMIDTIPO             NUMBER(8)       NOT NULL,
  STRTIPOGASTOMIN       VARCHAR2(2000)  NOT NULL,
  NUMIDTECNICA          NUMBER(8)       NULL
);

COMMENT ON TABLE TECNICOS_INV.TB_UC3M_INV_JUST_CONC_ENTIDAD IS 'Tabla que contiene los valores CTPCON y CTPSCO de cada concepto de la entidad financiadora para los distintos tipos de proyecto.';
COMMENT ON COLUMN TECNICOS_INV.TB_UC3M_INV_JUST_CONC_ENTIDAD.NUMIDCONCEPTOENTIDAD IS 'Identificador interno del código de la entidad para la ayuda.';
COMMENT ON COLUMN TECNICOS_INV.TB_UC3M_INV_JUST_CONC_ENTIDAD.STRCTPCON IS 'Valor del campo CTPCON del concepto de la entidad según documento de ayuda.';
COMMENT ON COLUMN TECNICOS_INV.TB_UC3M_INV_JUST_CONC_ENTIDAD.STRCTPSCO IS 'Valor del campo CTPSCO del concepto de la entidad según documento de ayuda.';
COMMENT ON COLUMN TECNICOS_INV.TB_UC3M_INV_JUST_CONC_ENTIDAD.NUMIDTIPO IS 'Identificador del tipo de ayuda según el documento.';
COMMENT ON COLUMN TECNICOS_INV.TB_UC3M_INV_JUST_CONC_ENTIDAD.STRTIPOGASTOMIN IS 'Descripción del tipo de gasto según documento de ayuda.';
COMMENT ON COLUMN TECNICOS_INV.TB_UC3M_INV_JUST_CONC_ENTIDAD.NUMIDTECNICA IS 'Identificador del tipo de gasto de la justificación técnica.';

CREATE UNIQUE INDEX TECNICOS_INV.JUST_CONCENTIDAD_PK_I ON TECNICOS_INV.TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD);
CREATE INDEX TECNICOS_INV.JUST_CONCENTIDAD_TIPO_FK_I ON TECNICOS_INV.TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDTIPO);
CREATE INDEX TECNICOS_INV.JUST_CONCENTIDAD_TEC_FK_I ON TECNICOS_INV.TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDTECNICA);

ALTER TABLE TECNICOS_INV.TB_UC3M_INV_JUST_CONC_ENTIDAD ADD (
  CONSTRAINT JUST_CONCENTIDAD_PK
  PRIMARY KEY (NUMIDCONCEPTOENTIDAD)
  USING INDEX TECNICOS_INV.JUST_CONCENTIDAD_PK_I
  ENABLE VALIDATE,
  CONSTRAINT JUST_CONCENTIDAD_TIPO_FK
  FOREIGN KEY (NUMIDTIPO) REFERENCES TECNICOS_INV.TB_UC3M_INV_JUST_TIPOS (NUMIDTIPO)
  ENABLE VALIDATE,
  CONSTRAINT JUST_CONCENTIDAD_TEC_FK
  FOREIGN KEY (NUMIDTECNICA) REFERENCES TECNICOS_INV.TB_UC3M_INV_JUST_TECNICA (NUMIDTECNICA)
  ENABLE VALIDATE
);

CREATE OR REPLACE TRIGGER TG_JUST_CONCENTIDAD_SQ
  BEFORE INSERT 
  ON TB_UC3M_INV_JUST_CONC_ENTIDAD FOR EACH ROW
BEGIN
  IF :new.NUMIDCONCEPTOENTIDAD IS NULL THEN
    SELECT JUST_CONCENTIDAD_SQ.nextval INTO :new.NUMIDCONCEPTOENTIDAD FROM DUAL;
  END IF;
END;
/
------------------------------------------------------
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (1, '52', '31', 36, 'Subcontrataciones', 5);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (2, '52', '31', 37, 'Subcontrataciones', 5);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (3, '52', '15', 36, 'Alquiler y mantenimiento de instrumental', 5);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (4, '52', '15', 37, 'Alquiler y mantenimiento de instrumental', 5);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (5, '1', '3', 1, 'Salario Bruto', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (6, '1', '3', 2, 'Salario Bruto', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (7, '1', '3', 8, 'Salario Bruto', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (8, '5', '1', 3, 'Salario Bruto', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (9, '1', '3', 4, 'Salario Bruto', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (10, '1', '4', 5, 'Salario Bruto', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (11, '1', '3', 5, 'Salario Bruto', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (12, '1', '3', 16, 'Salario Bruto', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (13, '1', '4', 1, 'Seguridad Social', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (14, '1', '4', 2, 'Seguridad Social', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (15, '1', '9', 2, 'Atrasos o Pagas Extras (sólo de 2008 en adelante)', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (16, '5', '2', 3, 'Seguridad Social', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (17, '1', '9', 3, 'Atrasos o Pagas Extras', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (18, '1', '4', 8, 'Seguridad Social', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (19, '1', '9', 8, 'Atrasos o Pagas Extras', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (20, '1', '3', 9, 'Salario Bruto', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (21, '1', '4', 9, 'Seguridad Social', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (22, '1', '9', 9, 'Atrasos o Pagas Extras', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (23, '1', '4', 4, 'Salario Bruto', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (24, '1', '3', 7, 'Salario Bruto', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (25, '1', '4', 7, 'Salario Bruto', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (26, '1', '4', 16, 'Seguridad Social', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (27, '52', '2', 31, 'Complementos Salariales', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (28, '1', '3', 38, 'Salario Bruto', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (29, '1', '4', 38, 'Seguridad Social', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (30, '1', '9', 38, 'Atrasos o Pagas Extras', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (31, '52', '10', 21, 'Otros gastos', 5);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (32, '1', '2', 26, 'Personal Contratado', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (33, '52', '10', 36, 'Otros gastos', 5);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (34, '2', '1', 2, 'Pequeño equipamiento y material bibliográfico', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (35, '2', '2', 2, 'Material fungible', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (36, '2', '3', 2, 'Viajes y dietas', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (37, '2', '9', 2, 'Otros gastos', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (38, '52', '12', 36, 'Salario Bruto', 1);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (39, '52', '4', 36, 'Seguridad Social', 1);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (40, '52', '7', 36, 'Adquisición de material inventariable', 2);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (41, '52', '5', 36, 'Material fungible', 3);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (42, '52', '6', 36, 'Viajes y Dietas', 4);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (43, '52', '12', 37, 'Salario Bruto', 1);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (44, '52', '4', 37, 'Seguridad Social', 1);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (45, '52', '10', 37, 'Otros gastos', 5);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (46, '52', '7', 37, 'Adquisición de material inventariable', 2);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (47, '52', '5', 37, 'Material fungible', 3);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (48, '52', '6', 37, 'Viajes y Dietas', 4);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (49, '1', '3', 3, 'Salario Bruto', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (50, '5', '3', 3, 'Financiación adicional - Pequeño equipamiento y material bibliográfico', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (51, '5', '4', 3, 'Financiación adicional - Material fungible', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (52, '5', '5', 3, 'Financiación adicional - Viajes y dietas', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (53, '5', '6', 3, 'Financiación adicional - Otros gastos', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (54, '52', '5', 39, 'Fungible Laboratorio', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (55, '52', '6', 39, 'Viajes, dietas e Inscripciones', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (56, '52', '31', 39, 'Subcontratación entidades, personal autónomo', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (57, '1', '4', 17, 'Personal contratado', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (58, '2', '9', 17, 'Otros gastos', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (59, '2', '1', 17, 'Pequeño equipamiento y material bibliográfico', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (60, '2', '2', 17, 'Material fungible', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (61, '2', '3', 17, 'Viajes y dietas', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (62, '55', '2', 14, 'Nueva contratación', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (63, '2', '22', 14, 'Otros costes', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (64, '55', '1', 14, 'Propio', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (65, '55', '5', 14, 'Propio', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (66, '2', '1', 14, 'Pequeño equipamiento', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (67, '2', '2', 14, 'Material fungible', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (68, '2', '3', 14, 'Viajes y dietas', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (69, '2', '25', 14, 'Subcontratación', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (70, '1', '17', 12, 'Gastos Personal', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (71, '6', '1', 12, 'Subcontratación', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (72, '7', '1', 12, 'Aparatos y Equipos', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (73, '7', '2', 12, 'Amortización Equipos Nuevos Adquiridos para el proyecto', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (74, '8', '1', 12, 'Materiales', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (75, '23', '1', 12, 'Viajes', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (76, '52', '5', 29, 'MATERIAL FUNGIBLE', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (77, '52', '6', 29, 'VIAJES Y DIETAS', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (78, '52', '19', 29, 'Consultoría y equivalente', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (79, '52', '12', 30, 'Salario Bruto', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (80, '52', '4', 30, 'Seguridad Social', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (81, '52', '10', 30, 'Otros gastos', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (82, '52', '7', 30, 'Material inventariable', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (83, '52', '5', 30, 'Material fungible', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (84, '52', '6', 30, 'Viajes y Dietas', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (85, '52', '12', 28, 'SALARIO BRUTO', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (86, '52', '4', 28, 'SEGURIDAD SOCIAL', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (87, '52', '29', 34, 'Equipo principal', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (88, '52', '6', 28, 'VIAJES Y DIETAS', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (89, '52', '30', 34, 'Accesorio o complementos', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (90, '52', '10', 34, 'OTROS', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (91, '1', '5', 1, 'Complemento Salarial', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (92, '2', '1', 1, 'Pequeño equipamiento y material bibliográfico', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (93, '2', '2', 1, 'Material fungible', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (94, '2', '3', 1, 'Viajes y dietas', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (95, '2', '9', 1, 'Otros gastos', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (96, '1', '2', 19, 'Personal Contratado', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (97, '52', '5', 25, 'MATERIAL FUNGIBLE', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (98, '52', '9', 28, 'Organización y actividades científicas', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (99, '52', '12', 32, 'Salario Bruto', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (100, '52', '4', 32, 'Seguridad Social', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (101, '52', '10', 32, 'Otros gastos', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (102, '52', '5', 32, 'Material fungible', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (103, '52', '6', 32, 'Viajes y Dietas', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (104, '52', '14', 32, 'Pequeño equipamiento y material bibliográfico', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (105, '1', '3', 33, 'Salario Bruto', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (106, '5', '1', 33, 'Salario Bruto', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (107, '1', '4', 33, 'Seguridad Social', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (108, '1', '9', 33, 'Atrasos o Pagas Extras', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (109, '5', '3', 33, 'Financiación adicional - Pequeño equipamiento y material bibliográfico', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (110, '5', '4', 33, 'Financiación adicional - Material fungible', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (111, '5', '5', 33, 'Financiación adicional - Viajes y dietas', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (112, '5', '6', 33, 'Financiación adicional - Otros gastos', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (113, '2', '3', 6, 'Viajes y dietas', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (114, '1', '5', 7, 'Complemento Salarial', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (115, '2', '1', 7, 'Pequeño equipamiento y material bibliográfico', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (116, '2', '2', 7, 'Material fungible', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (117, '2', '3', 7, 'Viajes y dietas', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (118, '2', '9', 7, 'Otros gastos', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (119, '52', '11', 21, 'GASTOS DE INFORME DE AUDITORÍA', 5);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (120, '52', '11', 36, 'GASTOS DE INFORME DE AUDITORÍA', 5);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (121, '52', '11', 37, 'GASTOS DE INFORME DE AUDITORÍA', 5);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (122, '52', '10', 22, 'Otros gastos', 5);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (123, '52', '11', 22, 'GASTOS DE INFORME DE AUDITORÍA', 5);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (124, '27', '1', 26, 'AUDITORÍA DE CUENTAS', 5);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (125, '2', '9', 4, 'Otros gastos', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (126, '2', '9', 5, 'Otros gastos', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (127, '2', '1', 5, 'Pequeño equipamiento y material bibliográfico', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (128, '2', '2', 5, 'Material fungible', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (129, '2', '3', 5, 'Viajes y dietas', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (130, '52', '12', 20, 'Salario Bruto', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (131, '6', '1', 19, 'SUBCONTRATACIONES', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (132, '7', '5', 19, 'COMPRA', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (133, '7', '3', 19, 'Amortización Equipos Antiguos', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (134, '8', '1', 19, 'MATERIALES/FUNGIBLE', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (135, '9', '2', 19, 'VIAJES', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (136, '52', '4', 20, 'Seguridad Social', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (137, '52', '6', 20, 'Viajes y Dietas', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (138, '52', '12', 21, 'Salario Bruto', 1);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (139, '52', '4', 21, 'Seguridad Social', 1);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (140, '52', '7', 21, 'Adquisición de material inventariable', 2);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (141, '52', '5', 21, 'Material fungible', 3);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (142, '52', '6', 21, 'Viajes y Dietas', 4);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (143, '52', '12', 22, 'Salario Bruto', 1);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (144, '52', '4', 22, 'Seguridad Social', 1);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (145, '52', '7', 22, 'Adquisición de material inventariable', 2);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (146, '52', '5', 22, 'Material fungible', 3);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (147, '52', '6', 22, 'Viajes y Dietas', 4);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (148, '52', '12', 23, 'Salario Bruto', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (149, '52', '4', 23, 'Seguridad Social', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (150, '52', '10', 23, 'Otros gastos', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (151, '52', '7', 23, 'Adquisición de material inventariable', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (152, '52', '5', 23, 'Material fungible', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (153, '52', '6', 23, 'Viajes y Dietas', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (154, '21', '1', 24, 'Ayudas para estancias', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (155, '20', '1', 24, 'Viajes', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (156, '52', '6', 25, 'VIAJES Y DIETAS', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (157, '52', '19', 25, 'Consultoría y equivalente', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (158, '9', '2', 26, 'VIAJES', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (159, '6', '1', 26, 'SUBCONTRATACIONES', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (160, '8', '1', 26, 'MATERIALES/FUNGIBLE', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (161, '52', '12', 27, 'SALARIO BRUTO', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (162, '52', '4', 27, 'SEGURIDAD SOCIAL', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (163, '52', '5', 27, 'MATERIAL FUNGIBLE', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (164, '52', '6', 27, 'VIAJES Y DIETAS', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (165, '52', '19', 27, 'Consultoría y equivalente', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (166, '52', '10', 27, 'Otros gastos incluidos sociedades internacionales', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (167, '2', '9', 16, 'Otros gastos', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (168, '1', '5', 16, 'Complemento Salarial', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (169, '1', '17', 10, 'Gastos Personal', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (170, '6', '1', 10, 'Subcontratación', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (171, '7', '1', 10, 'Equipamiento científico y técnico', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (172, '7', '3', 10, 'Amortización Equipos Adquiridos con anterioridad al proyecto', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (173, '8', '1', 10, 'Materiales', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (174, '9', '2', 10, 'Viajes', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (175, '72', '2', 26, 'APARATOS Y EQUIPOS NUEVOS', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (176, '52', '12', 31, 'SALARIO BRUTO', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (177, '52', '4', 31, 'SEGURIDAD SOCIAL', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (178, '52', '3', 31, 'Pagas extras o atrasos', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (179, '52', '10', 31, 'Otros gastos', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (180, '52', '7', 31, 'Bienes inventariables', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (181, '52', '5', 31, 'MATERIAL FUNGIBLE', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (182, '52', '6', 31, 'VIAJES Y DIETAS', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (183, '52', '8', 31, 'Contratación: consultoría, asistencia o servicios', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (184, '2', '1', 4, 'Pequeño equipamiento y material bibliográfico', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (185, '2', '2', 4, 'Material fungible', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (186, '2', '3', 4, 'Viajes y dietas', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (187, '1', '4', 18, 'Seguridad Social', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (188, '1', '3', 18, 'Salario Bruto', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (189, '1', '3', 35, 'Contrato IP - Salario Bruto', 1);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (190, '1', '4', 35, 'Contrato IP - Seguridad Social', 1);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (191, '1', '9', 35, 'Contrato IP - Atrasos o Pagas Extra', 1);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (192, '2', '1', 16, 'Pequeño equipamiento y material bibliográfico', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (193, '2', '2', 16, 'Material fungible', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (194, '2', '3', 16, 'Viajes y dietas', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (195, '23', '7', 35, 'Otros Costes Directos - Otros gastos', 5);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (196, '2', '9', 18, 'Otros gastos', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (197, '2', '1', 18, 'Equipamiento informático', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (198, '2', '2', 18, 'Gastos Funcionamiento', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (199, '2', '3', 18, 'Viajes y dietas', NULL);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (200, '23', '12', 35, 'Otros Costes Directos - Adquisición de material inventariable', 2);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (201, '23', '8', 35, 'Otros Costes Directos - Material fungible', 3);
INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA) VALUES (202, '23', '1', 35, 'Otros Costes Directos - Viajes y Dietas', 4);

COMMIT;
