CREATE TABLE TB_UC3M_INV_JUST_FICHEROS_AGR (
  NUMIDFICHEROAGR		INT		NOT NULL AUTO_INCREMENT COMMENT 'Identificador del fichero generado en el lanzamiento de la agrupación.',
  NUMIDAGRUPACION		INT		NOT NULL COMMENT 'Identificador de la agrupación de proyectos.',
  NUMIDFICHERO	     	INT   	NOT NULL COMMENT 'Identificador del fichero asociado.',
  PRIMARY KEY (NUMIDFICHEROAGR),
  UNIQUE INDEX PROYECTOSJUST_UK (NUMIDAGRUPACION, NUMIDFICHERO),
  FOREIGN KEY JUST_FICAGR_AGR_FK (NUMIDAGRUPACION) REFERENCES TB_UC3M_INV_JUST_AGRUPACION (NUMIDAGRUPACION),
  FOREIGN KEY JUST_FICAGR_FIC_FK (NUMIDFICHERO) REFERENCES TB_UC3M_INV_JUST_FICHEROS (NUMIDFICHERO)
) COMMENT 'Tabla que contiene la relación de ficheros generados en el lanzamiento de una agrupación';
