CREATE TABLE TB_UC3M_INV_JUST_CONC_ENTIDAD_CC (
  NUMIDCONCEPTOENTIDAD INT	NOT NULL COMMENT 'Identificador interno del código para la ayuda',	
  NUMIDCONCEPTOCOSTE   INT	NOT NULL COMMENT 'Identificador  del concepto de coste genérico según la tabla TBINVPROCONCEPTOCOSTE',
  PRIMARY KEY (NUMIDCONCEPTOENTIDAD, NUMIDCONCEPTOCOSTE),
  FOREIGN KEY JUST_ENTIDADCC_ENTIDAD_FK (NUMIDCONCEPTOENTIDAD) REFERENCES TB_UC3M_INV_JUST_CONC_ENTIDAD (NUMIDCONCEPTOENTIDAD) ON UPDATE CASCADE,
  FOREIGN KEY JUST_ENTIDADCC_CC_FK (NUMIDCONCEPTOCOSTE) REFERENCES VWINVPROCONCEPTOCOSTE (NUMIDCONCEPTOCOSTE)
) COMMENT 'Tabla que contiene las relaciones entre los conceptos de la entidad financiadora y los conceptos de coste de la universidad';


UPDATE TB_UC3M_INV_JUST_CONC_ENTIDAD SET STRCTPCON=TRIM(STRCTPCON), STRCTPSCO=TRIM(STRCTPSCO)
WHERE STRCTPCON<>TRIM(STRCTPCON) OR STRCTPSCO<>TRIM(STRCTPSCO);

INSERT INTO TB_UC3M_INV_JUST_CONC_ENTIDAD_CC (NUMIDCONCEPTOENTIDAD, NUMIDCONCEPTOCOSTE)
SELECT DISTINCT NUMIDCONCEPTOENTIDAD, NUMIDCONCEPTOCOSTE FROM (
SELECT A.NUMIDCONCEPTOENTIDAD NUMIDCONCEPTOENTIDAD_OLD, B.NUMIDCONCEPTOENTIDAD, A.NUMIDCONCEPTOCOSTE, A.NUMIDTIPO, A.STRCTPCON, A.STRCTPSCO FROM TB_UC3M_INV_JUST_CONC_ENTIDAD A
JOIN (
SELECT MIN(NUMIDCONCEPTOENTIDAD) NUMIDCONCEPTOENTIDAD, NUMIDTIPO, STRCTPCON, STRCTPSCO FROM TB_UC3M_INV_JUST_CONC_ENTIDAD
GROUP BY NUMIDTIPO, STRCTPCON, STRCTPSCO
) B ON A.NUMIDTIPO=B.NUMIDTIPO AND A.STRCTPCON=B.STRCTPCON AND A.STRCTPSCO=B.STRCTPSCO) TMP;

DELETE FROM TB_UC3M_INV_JUST_CONC_ENTIDAD
WHERE NUMIDCONCEPTOENTIDAD NOT IN (
SELECT MIN(NUMIDCONCEPTOENTIDAD) FROM (SELECT * FROM TB_UC3M_INV_JUST_CONC_ENTIDAD) C
GROUP BY NUMIDTIPO, STRCTPCON, STRCTPSCO);

ALTER TABLE tb_uc3m_inv_just_conc_entidad DROP COLUMN NUMIDCONCEPTOCOSTE;

CREATE TABLE DUMMY AS
SELECT ITERATOR, NUMIDCONCEPTOENTIDAD FROM (
SELECT 
    @i:=@i+1 AS iterator, 
    t.*
FROM 
    tb_uc3m_inv_just_conc_entidad AS t,
    (SELECT @i:=0) AS foo) A;

UPDATE tb_uc3m_inv_just_conc_entidad A
SET A.NUMIDCONCEPTOENTIDAD=(
  SELECT B.ITERATOR FROM DUMMY B WHERE B.NUMIDCONCEPTOENTIDAD=A.NUMIDCONCEPTOENTIDAD
);

DROP TABLE DUMMY;

COMMIT;
