---------------------- MYSQL ------------------------
CREATE TABLE TB_UC3M_INV_JUST_CENTROS (
  NUMIDCENTRO       INT           NOT NULL AUTO_INCREMENT COMMENT 'Identificador interno del centro asociado para las ayudas.',
  NUMIDPROYECTO     INT           NOT NULL COMMENT 'Identificador del proyecto global asociado al proyecto de la ayuda según el ministerio.',
  NUMIDSUBPROYECTO  INT           NOT NULL COMMENT 'Identificador del proyecto de la ayuda según el ministerio.',
  STRCODIGOCENTRO   VARCHAR(20) 	NOT NULL COMMENT 'Código del centro',
  PRIMARY KEY JUST_CENTROS_PK (NUMIDCENTRO),
  UNIQUE KEY JUST_CENTROS_UK (NUMIDPROYECTO, NUMIDSUBPROYECTO),
  FOREIGN KEY JUST_CENTROS_PRY_FK (NUMIDPROYECTO, NUMIDSUBPROYECTO) REFERENCES VWINVPROSUBPROYECTO (NUMIDPROYECTO, NUMIDSUBPROYECTO)
) COMMENT 'Tabla que contiene los códigos de centro de la universidad asignados a los proyectos CONSOLIDER';
---------------------- ORACLE ------------------------
CREATE SEQUENCE TECNICOS_INV.JUST_CENTROS_SQ;

CREATE TABLE TECNICOS_INV.TB_UC3M_INV_JUST_CENTROS (
  NUMIDCENTRO       NUMBER(8)     NOT NULL,
  NUMIDPROYECTO     NUMBER(8)     NOT NULL,
  NUMIDSUBPROYECTO  NUMBER(8)     NOT NULL,
  STRCODIGOCENTRO   VARCHAR2(20)  NOT NULL
);

COMMENT ON TABLE TECNICOS_INV.TB_UC3M_INV_JUST_CENTROS IS 'Tabla que contiene los códigos de centro de la universidad asignados a los proyectos CONSOLIDER.';
COMMENT ON COLUMN TECNICOS_INV.TB_UC3M_INV_JUST_CENTROS.NUMIDCENTRO IS 'Identificador interno del centro asociado para las ayudas.';
COMMENT ON COLUMN TECNICOS_INV.TB_UC3M_INV_JUST_CENTROS.NUMIDPROYECTO IS 'Identificador del proyecto global asociado al proyecto de la ayuda según el ministerio.';
COMMENT ON COLUMN TECNICOS_INV.TB_UC3M_INV_JUST_CENTROS.NUMIDSUBPROYECTO IS 'Identificador del proyecto de la ayuda según el ministerio.';
COMMENT ON COLUMN TECNICOS_INV.TB_UC3M_INV_JUST_CENTROS.STRCODIGOCENTRO IS 'Código del centro.';

CREATE UNIQUE INDEX TECNICOS_INV.JUST_CENTROS_PK_I ON TECNICOS_INV.TB_UC3M_INV_JUST_CENTROS (NUMIDCENTRO);
CREATE UNIQUE INDEX TECNICOS_INV.JUST_CENTROS_UK_I ON TECNICOS_INV.TB_UC3M_INV_JUST_CENTROS (NUMIDPROYECTO, NUMIDSUBPROYECTO);

ALTER TABLE TECNICOS_INV.TB_UC3M_INV_JUST_CENTROS ADD (
  CONSTRAINT JUST_CENTROS_PK
  PRIMARY KEY (NUMIDCENTRO)
  USING INDEX TECNICOS_INV.JUST_CENTROS_PK_I
  ENABLE VALIDATE,
  CONSTRAINT JUST_CENTROS_UK
  UNIQUE (NUMIDPROYECTO, NUMIDSUBPROYECTO)
  USING INDEX TECNICOS_INV.JUST_CENTROS_UK_I
  ENABLE VALIDATE,
  CONSTRAINT JUST_CENTROS_PRY_FK
  FOREIGN KEY (NUMIDPROYECTO, NUMIDSUBPROYECTO) REFERENCES UXXIINV.TBINVPROSUBPROYECTO (NUMIDPROYECTO, NUMIDSUBPROYECTO)
  ENABLE VALIDATE
);

CREATE OR REPLACE TRIGGER TG_JUST_CENTROS_SQ
  BEFORE INSERT 
  ON TB_UC3M_INV_JUST_CENTROS FOR EACH ROW
BEGIN
  IF :new.NUMIDCENTRO IS NULL THEN
    SELECT JUST_CENTROS_SQ.nextval INTO :new.NUMIDCENTRO FROM DUAL;
  END IF;
END;
/
------------------------------------------------------
INSERT INTO TB_UC3M_INV_JUST_CENTROS (NUMIDPROYECTO, NUMIDSUBPROYECTO, STRCODIGOCENTRO) VALUES (5759, 6713, '46-0-0'); 
INSERT INTO TB_UC3M_INV_JUST_CENTROS (NUMIDPROYECTO, NUMIDSUBPROYECTO, STRCODIGOCENTRO) VALUES (6379, 7477, '46-59-0'); 
INSERT INTO TB_UC3M_INV_JUST_CENTROS (NUMIDPROYECTO, NUMIDSUBPROYECTO, STRCODIGOCENTRO) VALUES (4527, 5307, '46-24-0'); 
INSERT INTO TB_UC3M_INV_JUST_CENTROS (NUMIDPROYECTO, NUMIDSUBPROYECTO, STRCODIGOCENTRO) VALUES (4726, 5528, '46-0-0'); 
INSERT INTO TB_UC3M_INV_JUST_CENTROS (NUMIDPROYECTO, NUMIDSUBPROYECTO, STRCODIGOCENTRO) VALUES (4705, 5510, '46-0-0'); 
INSERT INTO TB_UC3M_INV_JUST_CENTROS (NUMIDPROYECTO, NUMIDSUBPROYECTO, STRCODIGOCENTRO) VALUES (4687, 5488, '46-0-0'); 
COMMIT;
