CREATE TABLE TB_UC3M_INV_JUST_CENTROS (
  NUMIDCENTRO INT 					NOT NULL AUTO_INCREMENT COMMENT 'Identificador interno del centro asociado para las ayudas',
  STRREFEXTPROYECTO  VARCHAR(50) 	NOT NULL COMMENT 'Referencia externa del proyecto y código de la ayuda según PN. Sirve para relacionar los datos del sistema con los del ministerio',
  STRCODIGOCENTRO    VARCHAR(20) 	NOT NULL COMMENT 'Código del centro',
  PRIMARY KEY (NUMIDCENTRO),
  UNIQUE KEY PROYECTO_UNIQUE (STRREFEXTPROYECTO)
) COMMENT 'Tabla que contiene los códigos de centro de la universidad asignados a los proyectos CONSOLIDER';

Insert into TB_UC3M_INV_JUST_CENTROS (STRREFEXTPROYECTO, STRCODIGOCENTRO)
 Values ('CSD2009-00067', '46-0-0');
Insert into TB_UC3M_INV_JUST_CENTROS (STRREFEXTPROYECTO, STRCODIGOCENTRO)
 Values ('CSD2010-00011', '46-59-0');
Insert into TB_UC3M_INV_JUST_CENTROS (STRREFEXTPROYECTO, STRCODIGOCENTRO)
 Values ('CSD2008-00007', '46-24-0');
Insert into TB_UC3M_INV_JUST_CENTROS (STRREFEXTPROYECTO, STRCODIGOCENTRO)
 Values ('CSD2008-00077', '46-0-0');
Insert into TB_UC3M_INV_JUST_CENTROS (STRREFEXTPROYECTO, STRCODIGOCENTRO)
 Values ('CSD2008-00068', '46-0-0');
Insert into TB_UC3M_INV_JUST_CENTROS (STRREFEXTPROYECTO, STRCODIGOCENTRO)
 Values ('CSD2008-00010', '46-0-0');
COMMIT;
