---------------------- MYSQL ------------------------
CREATE TABLE TB_UC3M_INV_JUST_CENTROS (
  NUMIDCENTRO INT 					NOT NULL AUTO_INCREMENT COMMENT 'Identificador interno del centro asociado para las ayudas',
  STRREFEXTPROYECTO  VARCHAR(50) 	NOT NULL COMMENT 'Referencia externa del proyecto y código de la ayuda según PN. Sirve para relacionar los datos del sistema con los del ministerio',
  STRCODIGOCENTRO    VARCHAR(20) 	NOT NULL COMMENT 'Código del centro',
  PRIMARY KEY (NUMIDCENTRO),
  UNIQUE KEY PROYECTO_UNIQUE (STRREFEXTPROYECTO)
) COMMENT 'Tabla que contiene los códigos de centro de la universidad asignados a los proyectos CONSOLIDER';
---------------------- ORACLE ------------------------
CREATE SEQUENCE TECNICOS_INV.JUST_CENTROS_SQ;

CREATE TABLE TECNICOS_INV.TB_UC3M_INV_JUST_CENTROS (
  NUMIDCENTRO       NUMBER(8)     NOT NULL,
  STRREFEXTPROYECTO VARCHAR2(50)  NOT NULL,
  STRCODIGOCENTRO   VARCHAR2(20)  NOT NULL
);

COMMENT ON TABLE TECNICOS_INV.TB_UC3M_INV_JUST_CENTROS IS 'Tabla que contiene los códigos de centro de la universidad asignados a los proyectos CONSOLIDER.';
COMMENT ON COLUMN TECNICOS_INV.TB_UC3M_INV_JUST_CENTROS.NUMIDCENTRO IS 'Identificador interno del centro asociado para las ayudas.';
COMMENT ON COLUMN TECNICOS_INV.TB_UC3M_INV_JUST_CENTROS.STRREFEXTPROYECTO IS 'Referencia externa del proyecto y código de la ayuda según PN. Sirve para relacionar los datos del sistema con los del ministerio.';
COMMENT ON COLUMN TECNICOS_INV.TB_UC3M_INV_JUST_CENTROS.STRCODIGOCENTRO IS 'Código del centro.';

CREATE UNIQUE INDEX TECNICOS_INV.JUST_CENTROS_PK_I ON TECNICOS_INV.TB_UC3M_INV_JUST_CENTROS (NUMIDCENTRO);

ALTER TABLE TECNICOS_INV.TB_UC3M_INV_JUST_CENTROS ADD (
  CONSTRAINT JUST_CENTROS_PK
  PRIMARY KEY (NUMIDCENTRO)
  USING INDEX TECNICOS_INV.JUST_CENTROS_PK_I
  ENABLE VALIDATE
);

CREATE OR REPLACE TRIGGER TG_JUST_CENTROS_SQ
  BEFORE INSERT 
  ON TB_UC3M_INV_JUST_CENTROS FOR EACH ROW
BEGIN
  IF :new.NUMIDCENTRO IS NULL THEN
    SELECT JUST_CENTROS_SQ.nextval INTO :new.NUMIDCENTRO FROM DUAL;
  END IF;
END;
/
------------------------------------------------------
Insert into TB_UC3M_INV_JUST_CENTROS (STRREFEXTPROYECTO, STRCODIGOCENTRO)
 Values ('CSD2009-00067', '46-0-0');
Insert into TB_UC3M_INV_JUST_CENTROS (STRREFEXTPROYECTO, STRCODIGOCENTRO)
 Values ('CSD2010-00011', '46-59-0');
Insert into TB_UC3M_INV_JUST_CENTROS (STRREFEXTPROYECTO, STRCODIGOCENTRO)
 Values ('CSD2008-00007', '46-24-0');
Insert into TB_UC3M_INV_JUST_CENTROS (STRREFEXTPROYECTO, STRCODIGOCENTRO)
 Values ('CSD2008-00077', '46-0-0');
Insert into TB_UC3M_INV_JUST_CENTROS (STRREFEXTPROYECTO, STRCODIGOCENTRO)
 Values ('CSD2008-00068', '46-0-0');
Insert into TB_UC3M_INV_JUST_CENTROS (STRREFEXTPROYECTO, STRCODIGOCENTRO)
 Values ('CSD2008-00010', '46-0-0');
COMMIT;
