CREATE TABLE TB_UC3M_INV_JUST_CODIGOS (
  NUMIDCODIGO		INT				NOT NULL AUTO_INCREMENT COMMENT 'Identificador interno del código para la ayuda',	
  NUMIDCONCEPTOCOSTE  INT		    NOT NULL COMMENT 'Identificador  del concepto de coste genérico según la tabla TBINVPROCONCEPTOCOSTE',
  STRCTPCON         VARCHAR(2)     	NOT NULL COMMENT 'Valor del campo CTPCON del Plan Nacional según documento de ayuda',
  STRCTPSCO         VARCHAR(2)     	NOT NULL COMMENT 'Valor del campo CTPSCO del Plan Nacional según documento de ayuda',
  NUMIDTIPO         INT				NOT NULL COMMENT 'Identificador del tipo de ayuda según el PN',
  STRTIPOGASTOMIN   VARCHAR(2000)  	NOT NULL COMMENT 'Descripción del tipo de gasto según documento de ayuda',
  NUMIDTECNICA      INT				COMMENT 'Identificador del tipo de gasto de la justificación técnica',
  PRIMARY KEY (NUMIDCODIGO),
  UNIQUE KEY CODIGO_UK (NUMIDCONCEPTOCOSTE, NUMIDTIPO),
  FOREIGN KEY PN_COD_CC_FK (NUMIDCONCEPTOCOSTE) REFERENCES TBINVPROCONCEPTOCOSTE (NUMIDCONCEPTOCOSTE),
  FOREIGN KEY PN_COD_TEC_FK (NUMIDTECNICA) REFERENCES TB_UC3M_INV_JUST_TECNICA (NUMIDTECNICA),
  FOREIGN KEY PN_COD_TIPO_FK (NUMIDTIPO) REFERENCES TB_UC3M_INV_JUST_TIPOS (NUMIDTIPO)
) COMMENT 'Tabla que contiene los valores CTPCON y CTPSCO en cada tipo de proyecto del PN para los distintos conceptos de gastos de la universidad';

Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (302, '52', '31', 36, 'Subcontrataciones', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (302, '52', '31', 37, 'Subcontrataciones', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (300, '52', '15', 36, 'Alquiler y mantenimiento de instrumental', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (301, '52', '15', 36, 'Alquiler y mantenimiento de instrumental', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (300, '52', '15', 37, 'Alquiler y mantenimiento de instrumental', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (301, '52', '15', 37, 'Alquiler y mantenimiento de instrumental', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (16, '1 ', '3 ', 1, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (117, '1', '3', 2, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (16, '1 ', '3 ', 2, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (113, '1', '3', 8, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (16, '5', '1', 3, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (117, '1', '3', 8, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (16, '1 ', '3 ', 4, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (183, '1', '4', 5, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (16, '1 ', '3 ', 5, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (151, '1', '3', 16, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (113, '1', '3', 1, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (117, '1', '3', 1, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (114, '1', '4', 1, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (182, '1', '4', 1, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (155, '1', '4', 1, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (151, '1', '3', 1, 'Atrasos o Pagas Extras (sólo de 2008 en adelante)');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (183, '1', '3', 1, 'Atrasos o Pagas Extras (sólo de 2008 en adelante)');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (184, '1', '3', 1, 'Atrasos o Pagas Extras (sólo de 2008 en adelante)');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (113, '1', '3', 2, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (114, '1', '4', 2, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (182, '1', '4', 2, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (155, '1', '4', 2, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (151, '1', '3', 2, 'Atrasos o Pagas Extras (sólo de 2008 en adelante)');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (183, '1', '9', 2, 'Atrasos o Pagas Extras (sólo de 2008 en adelante)');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (184, '1', '9', 2, 'Atrasos o Pagas Extras (sólo de 2008 en adelante)');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (113, '5', '1', 3, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (117, '5', '1', 3, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (114, '5', '2', 3, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (182, '5', '2', 3, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (155, '5', '2', 3, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (151, '1', '9', 3, 'Atrasos o Pagas Extras');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (183, '1', '9', 3, 'Atrasos o Pagas Extras');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (184, '1', '9', 3, 'Atrasos o Pagas Extras');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (114, '1', '4', 8, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (182, '1', '4', 8, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (155, '1', '4', 8, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (151, '1', '3', 8, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (183, '1', '9', 8, 'Atrasos o Pagas Extras');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (184, '1', '9', 8, 'Atrasos o Pagas Extras');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (113, '1', '3', 9, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (117, '1', '3', 9, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (114, '1', '4', 9, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (182, '1', '4', 9, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (155, '1', '4', 9, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (151, '1', '3', 9, 'Atrasos o Pagas Extras');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (183, '1', '9', 9, 'Atrasos o Pagas Extras');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (184, '1', '9', 9, 'Atrasos o Pagas Extras');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (113, '1', '3', 4, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (151, '1', '4', 4, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (183, '1', '4', 4, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (184, '1', '4', 4, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (117, '1', '3', 4, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (114, '1', '4', 4, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (182, '1', '4', 4, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (155, '1', '4', 4, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (151, '1', '4', 5, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (184, '1', '4', 5, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (117, '1', '3', 5, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (114, '1', '4', 5, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (182, '1', '4', 5, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (155, '1', '4', 5, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (113, '1', '3', 5, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (113, '1', '3', 7, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (151, '1', '4', 7, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (183, '1', '4', 7, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (184, '1', '4', 7, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (117, '1', '3', 7, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (114, '1', '4', 7, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (182, '1', '4', 7, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (155, '1', '4', 7, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (113, '1', '3', 16, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (183, '1', '3', 16, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (184, '1', '3', 16, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (117, '1', '3', 16, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (114, '1', '4', 16, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (182, '1', '4', 16, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (155, '1', '4', 16, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (121, '52', '2', 31, 'Complementos Salariales');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (113, '1', '3', 38, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (114, '1', '4', 38, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (184, '1', '9', 38, 'Atrasos o Pagas Extras');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (1, '1 ', '3 ', 2, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (11, '1 ', '3 ', 2, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (140, '52', '10', 21, 'Otros gastos', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (112, '1', '2', 26, 'Personal Contratado');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (140, '52', '10', 36, 'Otros gastos', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (38, '2 ', '1 ', 2, 'Pequeño equipamiento y material bibliográfico');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (125, '2 ', '1 ', 2, 'Pequeño equipamiento y material bibliográfico');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (54, '2 ', '2 ', 2, 'Material fungible');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (131, '2 ', '2 ', 2, 'Material fungible');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (63, '2 ', '3 ', 2, 'Viajes y dietas');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (134, '2 ', '3 ', 2, 'Viajes y dietas');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (49, '2 ', '9 ', 2, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (70, '2 ', '9 ', 2, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (88, '2 ', '9 ', 2, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (137, '2 ', '9 ', 2, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (141, '2 ', '9 ', 2, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (113, '52', '12', 36, 'Salario Bruto', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (114, '52', '4', 36, 'Seguridad Social', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (151, '52', '12', 36, 'Salario Bruto', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (183, '52', '12', 36, 'Salario Bruto', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (184, '52', '12', 36, 'Salario Bruto', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (117, '52', '12', 36, 'Salario Bruto', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (182, '52', '4', 36, 'Seguridad Social', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (155, '52', '4', 36, 'Seguridad Social', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (122, '52', '10', 36, 'Otros gastos', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (125, '52', '7', 36, 'Adquisición de material inventariable', 2);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (131, '52', '5', 36, 'Material fungible', 3);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (134, '52', '6', 36, 'Viajes y Dietas', 4);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (139, '52', '10', 36, 'Otros gastos', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (141, '52', '10', 36, 'Otros gastos', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (156, '52', '10', 36, 'Otros gastos', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (113, '52', '12', 37, 'Salario Bruto', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (114, '52', '4', 37, 'Seguridad Social', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (151, '52', '12', 37, 'Salario Bruto', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (183, '52', '12', 37, 'Salario Bruto', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (184, '52', '12', 37, 'Salario Bruto', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (117, '52', '12', 37, 'Salario Bruto', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (182, '52', '4', 37, 'Seguridad Social', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (155, '52', '4', 37, 'Seguridad Social', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (122, '52', '10', 37, 'Otros gastos', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (125, '52', '7', 37, 'Adquisición de material inventariable', 2);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (131, '52', '5', 37, 'Material fungible', 3);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (134, '52', '6', 37, 'Viajes y Dietas', 4);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (139, '52', '10', 37, 'Otros gastos', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (141, '52', '10', 37, 'Otros gastos', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (156, '52', '10', 37, 'Otros gastos', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (187, '52', '10', 36, 'Otros gastos', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (187, '52', '10', 37, 'Otros gastos', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (138, '52', '10', 37, 'Otros gastos', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (138, '52', '10', 36, 'Otros gastos', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (1, '1 ', '3 ', 3, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (11, '5', '1', 3, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (38, '5 ', '3 ', 3, 'Financiación adicional - Pequeño equipamiento y material bibliográfico');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (125, '5 ', '3 ', 3, 'Financiación adicional - Pequeño equipamiento y material bibliográfico');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (54, '5 ', '4 ', 3, 'Financiación adicional - Material fungible');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (131, '5 ', '4 ', 3, 'Financiación adicional - Material fungible');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (63, '5 ', '5 ', 3, 'Financiación adicional - Viajes y dietas');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (134, '5 ', '5 ', 3, 'Financiación adicional - Viajes y dietas');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (49, '5 ', '6 ', 3, 'Financiación adicional - Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (70, '5 ', '6 ', 3, 'Financiación adicional - Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (88, '5 ', '6 ', 3, 'Financiación adicional - Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (137, '5 ', '6 ', 3, 'Financiación adicional - Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (141, '5 ', '6 ', 3, 'Financiación adicional - Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (133, '52', '5', 39, 'Fungible Laboratorio');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (150, '52', '5', 39, 'Otro Material no inventariable/Licencias de uso de SW');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (134, '52', '6', 39, 'Viajes, dietas e Inscripciones');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (138, '52', '31', 39, 'Subcontratación entidades, personal autónomo');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (148, '52', '31', 39, 'Otros Servicios');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (112, '1', '4', 17, 'Personal contratado');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (118, '2 ', '9 ', 17, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (125, '2 ', '1 ', 17, 'Pequeño equipamiento y material bibliográfico');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (131, '2 ', '2 ', 17, 'Material fungible');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (134, '2 ', '3 ', 17, 'Viajes y dietas');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (137, '2 ', '9 ', 17, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (141, '2 ', '9 ', 17, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (151, '55', '2', 14, 'Nueva contratación');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (113, '55', '2', 14, 'Nueva contratación');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (183, '55', '2', 14, 'Nueva contratación');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (184, '55', '2', 14, 'Nueva contratación');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (114, '55', '2', 14, 'Nueva contratación');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (122, '2', '22', 14, 'Otros costes');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (120, '55', '1', 14, 'Propio');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (121, '55', '1', 14, 'Propio');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (123, '55', '1', 14, 'Propio');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (124, '55', '1', 14, 'Propio');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (186, '55', '5 ', 14, 'Propio');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (125, '2 ', '1 ', 14, 'Pequeño equipamiento');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (131, '2 ', '2 ', 14, 'Material fungible');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (134, '2 ', '3 ', 14, 'Viajes y dietas');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (141, '2 ', '22', 14, 'Otros costes');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (137, '2 ', '25', 14, 'Subcontratación');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (88, '2 ', '22', 14, 'Otros costes');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (156, '2 ', '22', 14, 'Otros costes');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (112, '1 ', '17', 12, 'Gastos Personal');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (137, '6 ', '1 ', 12, 'Subcontratación');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (125, '7 ', '1 ', 12, 'Aparatos y Equipos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (46, '7 ', '2 ', 12, 'Amortización Equipos Nuevos Adquiridos para el proyecto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (131, '8 ', '1 ', 12, 'Materiales');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (134, '23', '1 ', 12, 'Viajes');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (131, '52', '5', 29, 'MATERIAL FUNGIBLE');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (134, '52', '6', 29, 'VIAJES Y DIETAS');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (138, '52', '19', 29, 'Consultoría y equivalente');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (113, '52', '12', 30, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (114, '52', '4', 30, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (151, '52', '12', 30, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (183, '52', '12', 30, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (184, '52', '12', 30, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (117, '52', '12', 30, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (182, '52', '4', 30, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (155, '52', '4', 30, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (122, '52', '10', 30, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (125, '52', '7', 30, 'Material inventariable');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (131, '52', '5', 30, 'Material fungible');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (134, '52', '6', 30, 'Viajes y Dietas');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (137, '52', '10', 30, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (141, '52', '10', 30, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (156, '52', '10', 30, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (113, '52', '12', 28, 'SALARIO BRUTO');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (114, '52', '4', 28, 'SEGURIDAD SOCIAL');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (151, '52', '12', 28, 'SALARIO BRUTO');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (183, '52', '12', 28, 'SALARIO BRUTO');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (184, '52', '12', 28, 'SALARIO BRUTO');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (117, '52', '12', 28, 'SALARIO BRUTO');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (182, '52', '4', 28, 'SEGURIDAD SOCIAL');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (155, '52', '4', 28, 'SEGURIDAD SOCIAL');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (126, '52', '29', 34, 'Equipo principal');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (127, '52', '29', 34, 'Equipo principal');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (129, '52', '29', 34, 'Equipo principal');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (134, '52', '6', 28, 'VIAJES Y DIETAS');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (130, '52', '29', 34, 'Equipo principal');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (150, '52', '29', 34, 'Equipo principal');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (133, '52', '30', 34, 'Accesorio o complementos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (138, '52', '10', 34, 'OTROS');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (128, '52', '30', 34, 'Accesorio o complementos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (1, '1 ', '3 ', 1, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (11, '1 ', '3 ', 1, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (20, '1 ', '5 ', 1, 'Complemento Salarial');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (29, '1 ', '5 ', 1, 'Complemento Salarial');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (186, '1 ', '5 ', 1, 'Complemento Salarial');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (38, '2 ', '1 ', 1, 'Pequeño equipamiento y material bibliográfico');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (125, '2 ', '1 ', 1, 'Pequeño equipamiento y material bibliográfico');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (54, '2 ', '2 ', 1, 'Material fungible');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (131, '2 ', '2 ', 1, 'Material fungible');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (63, '2 ', '3 ', 1, 'Viajes y dietas');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (134, '2 ', '3 ', 1, 'Viajes y dietas');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (49, '2 ', '9 ', 1, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (70, '2 ', '9 ', 1, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (88, '2 ', '9 ', 1, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (137, '2 ', '9 ', 1, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (141, '2 ', '9 ', 1, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (112, '1', '2', 19, 'Personal Contratado');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (128, '52', '5', 25, 'MATERIAL FUNGIBLE');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (145, '52', '5', 25, 'MATERIAL FUNGIBLE');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (147, '52', '5', 25, 'MATERIAL FUNGIBLE');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (138, '52', '9', 28, 'Organización y actividades científicas');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (148, '52', '19', 29, 'Consultoría y equivalente');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (113, '52', '12', 32, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (114, '52', '4', 32, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (151, '52', '12', 32, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (183, '52', '12', 32, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (184, '52', '12', 32, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (117, '52', '12', 32, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (182, '52', '4', 32, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (155, '52', '4', 32, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (122, '52', '10', 32, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (131, '52', '5', 32, 'Material fungible');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (134, '52', '6', 32, 'Viajes y Dietas');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (137, '52', '10', 32, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (141, '52', '10', 32, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (156, '52', '10', 32, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (125, '52', '14', 32, 'Pequeño equipamiento y material bibliográfico');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (113, '1', '3', 33, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (151, '5', '1', 33, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (117, '1', '3', 33, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (114, '1', '4', 33, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (182, '1', '4', 33, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (155, '1', '4', 33, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (183, '1', '9', 33, 'Atrasos o Pagas Extras');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (184, '1', '9', 33, 'Atrasos o Pagas Extras');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (125, '5', '3', 33, 'Financiación adicional - Pequeño equipamiento y material bibliográfico');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (131, '5', '4', 33, 'Financiación adicional - Material fungible');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (134, '5', '5', 33, 'Financiación adicional - Viajes y dietas');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (137, '5', '6', 33, 'Financiación adicional - Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (141, '5', '6', 33, 'Financiación adicional - Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (118, '5', '6', 33, 'Financiación adicional - Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (63, '2 ', '3 ', 6, 'Viajes y dietas');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (134, '2 ', '3 ', 6, 'Viajes y dietas');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (138, '52', '10', 21, 'Otros gastos', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (16, '1 ', '3 ', 7, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (139, '52', '10', 21, 'Otros gastos', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (1, '1 ', '3 ', 7, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (11, '1 ', '3 ', 7, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (20, '1 ', '5 ', 7, 'Complemento Salarial');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (29, '1 ', '5 ', 7, 'Complemento Salarial');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (186, '1 ', '5 ', 7, 'Complemento Salarial');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (38, '2 ', '1 ', 7, 'Pequeño equipamiento y material bibliográfico');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (125, '2 ', '1 ', 7, 'Pequeño equipamiento y material bibliográfico');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (54, '2 ', '2 ', 7, 'Material fungible');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (131, '2 ', '2 ', 7, 'Material fungible');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (63, '2 ', '3 ', 7, 'Viajes y dietas');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (134, '2 ', '3 ', 7, 'Viajes y dietas');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (49, '2 ', '9 ', 7, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (70, '2 ', '9 ', 7, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (88, '2 ', '9 ', 7, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (137, '2 ', '9 ', 7, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (141, '2 ', '9 ', 7, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (156, '2 ', '9 ', 7, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (314, '52', '11', 21, 'GASTOS DE INFORME DE AUDITORÍA', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (187, '52', '10', 21, 'Otros gastos', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (300, '52', '10', 21, 'Otros gastos', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (301, '52', '10', 21, 'Otros gastos', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (302, '52', '10', 21, 'Otros gastos', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (314, '52', '11', 36, 'GASTOS DE INFORME DE AUDITORÍA', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (314, '52', '11', 37, 'GASTOS DE INFORME DE AUDITORÍA', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (138, '52', '10', 22, 'Otros gastos', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (139, '52', '10', 22, 'Otros gastos', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (187, '52', '10', 22, 'Otros gastos', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (300, '52', '10', 22, 'Otros gastos', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (301, '52', '10', 22, 'Otros gastos', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (302, '52', '10', 22, 'Otros gastos', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (314, '52', '11', 22, 'GASTOS DE INFORME DE AUDITORÍA', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (314, '27', '1', 26, 'AUDITORÍA DE CUENTAS', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (20, '2 ', '9 ', 2, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (29, '2 ', '9 ', 2, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (118, '2 ', '9 ', 2, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (20, '2 ', '9 ', 4, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (29, '2 ', '9 ', 4, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (118, '2 ', '9 ', 4, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (20, '2 ', '9 ', 5, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (29, '2 ', '9 ', 5, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (118, '2 ', '9 ', 5, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (20, '5 ', '6 ', 3, 'Financiación adicional - Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (29, '5 ', '6 ', 3, 'Financiación adicional - Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (118, '5 ', '6 ', 3, 'Financiación adicional - Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (1, '1 ', '3 ', 5, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (11, '1 ', '3 ', 5, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (38, '2 ', '1 ', 5, 'Pequeño equipamiento y material bibliográfico');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (125, '2 ', '1 ', 5, 'Pequeño equipamiento y material bibliográfico');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (54, '2 ', '2 ', 5, 'Material fungible');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (131, '2 ', '2 ', 5, 'Material fungible');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (63, '2 ', '3 ', 5, 'Viajes y dietas');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (134, '2 ', '3 ', 5, 'Viajes y dietas');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (49, '2 ', '9 ', 5, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (70, '2 ', '9 ', 5, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (88, '2 ', '9 ', 5, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (137, '2 ', '9 ', 5, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (141, '2 ', '9 ', 5, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (113, '52', '12', 20, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (137, '6 ', '1 ', 19, 'SUBCONTRATACIONES');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (125, '7 ', '5', 19, 'COMPRA');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (46, '7 ', '3', 19, 'Amortización Equipos Antiguos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (131, '8 ', '1 ', 19, 'MATERIALES/FUNGIBLE');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (134, '9', '2', 19, 'VIAJES');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (114, '52', '4', 20, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (151, '52', '12', 20, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (183, '52', '12', 20, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (184, '52', '12', 20, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (134, '52', '6', 20, 'Viajes y Dietas');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (237, '52', '6', 20, 'Viajes y Dietas');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (238, '52', '6', 20, 'Viajes y Dietas');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (113, '52', '12', 21, 'Salario Bruto', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (114, '52', '4', 21, 'Seguridad Social', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (151, '52', '12', 21, 'Salario Bruto', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (183, '52', '12', 21, 'Salario Bruto', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (184, '52', '12', 21, 'Salario Bruto', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (117, '52', '12', 21, 'Salario Bruto', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (182, '52', '4', 21, 'Seguridad Social', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (155, '52', '4', 21, 'Seguridad Social', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (122, '52', '10', 21, 'Otros gastos', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (125, '52', '7', 21, 'Adquisición de material inventariable', 2);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (131, '52', '5', 21, 'Material fungible', 3);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (134, '52', '6', 21, 'Viajes y Dietas', 4);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (141, '52', '10', 21, 'Otros gastos', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (156, '52', '10', 21, 'Otros gastos', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (113, '52', '12', 22, 'Salario Bruto', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (114, '52', '4', 22, 'Seguridad Social', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (151, '52', '12', 22, 'Salario Bruto', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (183, '52', '12', 22, 'Salario Bruto', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (184, '52', '12', 22, 'Salario Bruto', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (117, '52', '12', 22, 'Salario Bruto', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (182, '52', '4', 22, 'Seguridad Social', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (155, '52', '4', 22, 'Seguridad Social', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (122, '52', '10', 22, 'Otros gastos', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (125, '52', '7', 22, 'Adquisición de material inventariable', 2);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (131, '52', '5', 22, 'Material fungible', 3);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (134, '52', '6', 22, 'Viajes y Dietas', 4);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (141, '52', '10', 22, 'Otros gastos', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (156, '52', '10', 22, 'Otros gastos', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (113, '52', '12', 23, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (114, '52', '4', 23, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (151, '52', '12', 23, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (183, '52', '12', 23, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (184, '52', '12', 23, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (117, '52', '12', 23, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (182, '52', '4', 23, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (155, '52', '4', 23, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (122, '52', '10', 23, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (125, '52', '7', 23, 'Adquisición de material inventariable');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (131, '52', '5', 23, 'Material fungible');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (134, '52', '6', 23, 'Viajes y Dietas');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (137, '52', '10', 23, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (141, '52', '10', 23, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (156, '52', '10', 23, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (236, '21', '1', 24, 'Ayudas para estancias');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (237, '21', '1', 24, 'Ayudas para estancias');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (238, '20', '1', 24, 'Viajes');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (131, '52', '5', 25, 'MATERIAL FUNGIBLE');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (134, '52', '6', 25, 'VIAJES Y DIETAS');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (138, '52', '19', 25, 'Consultoría y equivalente');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (134, '9', '2', 26, 'VIAJES');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (138, '6', '1', 26, 'SUBCONTRATACIONES');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (131, '8', '1', 26, 'MATERIALES/FUNGIBLE');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (113, '52', '12', 27, 'SALARIO BRUTO');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (114, '52', '4', 27, 'SEGURIDAD SOCIAL');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (151, '52', '12', 27, 'SALARIO BRUTO');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (183, '52', '12', 27, 'SALARIO BRUTO');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (184, '52', '12', 27, 'SALARIO BRUTO');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (131, '52', '5', 27, 'MATERIAL FUNGIBLE');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (134, '52', '6', 27, 'VIAJES Y DIETAS');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (138, '52', '19', 27, 'Consultoría y equivalente');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (148, '52', '10', 27, 'Otros gastos incluidos sociedades internacionales');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (156, '2 ', '9 ', 1, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (156, '2 ', '9 ', 2, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (122, '2', '9', 1, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (122, '2', '9', 7, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (122, '2', '9', 16, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (120, '1', '5', 1, 'Complemento Salarial');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (121, '1', '5', 1, 'Complemento Salarial');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (123, '1', '5', 1, 'Complemento Salarial');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (124, '1', '5', 1, 'Complemento Salarial');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (120, '1', '5', 7, 'Complemento Salarial');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (121, '1', '5', 7, 'Complemento Salarial');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (123, '1', '5', 7, 'Complemento Salarial');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (124, '1', '5', 7, 'Complemento Salarial');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (120, '1', '5', 16, 'Complemento Salarial');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (121, '1', '5', 16, 'Complemento Salarial');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (123, '1', '5', 16, 'Complemento Salarial');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (124, '1', '5', 16, 'Complemento Salarial');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (112, '1 ', '17', 10, 'Gastos Personal');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (137, '6 ', '1 ', 10, 'Subcontratación');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (125, '7 ', '1 ', 10, 'Equipamiento científico y técnico');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (46, '7 ', '3', 10, 'Amortización Equipos Adquiridos con anterioridad al proyecto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (131, '8 ', '1 ', 10, 'Materiales');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (134, '9', '2', 10, 'Viajes');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (125, '72', '2', 26, 'APARATOS Y EQUIPOS NUEVOS');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (113, '52', '12', 31, 'SALARIO BRUTO');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (114, '52', '4', 31, 'SEGURIDAD SOCIAL');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (151, '52', '12', 31, 'SALARIO BRUTO');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (183, '52', '3', 31, 'Pagas extras o atrasos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (184, '52', '3', 31, 'Pagas extras o atrasos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (117, '52', '12', 31, 'SALARIO BRUTO');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (182, '52', '4', 31, 'SEGURIDAD SOCIAL');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (155, '52', '4', 31, 'SEGURIDAD SOCIAL');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (122, '52', '10', 31, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (125, '52', '7', 31, 'Bienes inventariables');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (131, '52', '5', 31, 'MATERIAL FUNGIBLE');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (134, '52', '6', 31, 'VIAJES Y DIETAS');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (137, '52', '8', 31, 'Contratación: consultoría, asistencia o servicios');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (141, '52', '10', 31, 'OTROS GASTOS');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (156, '52', '10', 31, 'OTROS GASTOS');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (120, '52', '2', 31, 'Complementos Salariales');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (1, '1 ', '3 ', 4, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (11, '1 ', '3 ', 4, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (38, '2 ', '1 ', 4, 'Pequeño equipamiento y material bibliográfico');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (125, '2 ', '1 ', 4, 'Pequeño equipamiento y material bibliográfico');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (54, '2 ', '2 ', 4, 'Material fungible');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (131, '2 ', '2 ', 4, 'Material fungible');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (63, '2 ', '3 ', 4, 'Viajes y dietas');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (134, '2 ', '3 ', 4, 'Viajes y dietas');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (49, '2 ', '9 ', 4, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (70, '2 ', '9 ', 4, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (88, '2 ', '9 ', 4, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (137, '2 ', '9 ', 4, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (141, '2 ', '9 ', 4, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (183, '1', '4', 18, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (225, '52', '12', 20, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (16, '1 ', '3 ', 18, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (113, '1', '3', 35, 'Contrato IP - Salario Bruto', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (114, '1', '4', 35, 'Contrato IP - Seguridad Social', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (151, '1', '3', 35, 'Contrato IP - Salario Bruto', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (183, '1', '9', 35, 'Contrato IP - Atrasos o Pagas Extra', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (186, '1 ', '5 ', 16, 'Complemento Salarial');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (184, '1', '9', 35, 'Contrato IP - Atrasos o Pagas Extra', 1);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (125, '2 ', '1 ', 16, 'Pequeño equipamiento y material bibliográfico');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (131, '2 ', '2 ', 16, 'Material fungible');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (134, '2 ', '3 ', 16, 'Viajes y dietas');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (141, '2 ', '9 ', 16, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (137, '2 ', '9 ', 16, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (88, '2 ', '9 ', 16, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (156, '2 ', '9 ', 16, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (122, '23', '7', 35, 'Otros Costes Directos - Otros gastos', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (151, '1', '4', 18, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (184, '1', '4', 18, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (117, '1', '3', 18, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (114, '1', '4', 18, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (182, '1', '4', 18, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (155, '1', '4', 18, 'Seguridad Social');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (113, '1', '3', 18, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (20, '2 ', '9 ', 18, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (29, '2 ', '9 ', 18, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (118, '2 ', '9 ', 18, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (1, '1 ', '3 ', 18, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (11, '1 ', '3 ', 18, 'Salario Bruto');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (38, '2 ', '1 ', 18, 'Equipamiento informático');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (125, '2 ', '1 ', 18, 'Equipamiento informático');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (54, '2 ', '2 ', 18, 'Gastos Funcionamiento');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (131, '2 ', '2 ', 18, 'Gastos Funcionamiento');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (63, '2 ', '3 ', 18, 'Viajes y dietas');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (134, '2 ', '3 ', 18, 'Viajes y dietas');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (49, '2 ', '9 ', 18, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (70, '2 ', '9 ', 18, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (88, '2 ', '9 ', 18, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (137, '2 ', '9 ', 18, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN)
 Values
   (141, '2 ', '9 ', 18, 'Otros gastos');
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (125, '23', '12', 35, 'Otros Costes Directos - Adquisición de material inventariable', 2);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (131, '23', '8', 35, 'Otros Costes Directos - Material fungible', 3);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (134, '23', '1', 35, 'Otros Costes Directos - Viajes y Dietas', 4);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (137, '23', '7', 35, 'Otros Costes Directos - Otros gastos', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (141, '23', '7', 35, 'Otros Costes Directos - Otros gastos', 5);
Insert into TB_UC3M_INV_JUST_CODIGOS
   (NUMIDCONCEPTOCOSTE, STRCTPCON, STRCTPSCO, NUMIDTIPO, STRTIPOGASTOMIN, NUMIDTECNICA)
 Values
   (156, '23', '7', 35, 'Otros Costes Directos - Otros gastos', 5);
COMMIT;
