---------------------- MYSQL ------------------------
CREATE TABLE TB_UC3M_INV_JUST_FICHEROS (
  NUMIDFICHERO		INT			      NOT NULL AUTO_INCREMENT COMMENT 'Identificador del fichero.',
  STRDESCRIPCION	VARCHAR(2000) NOT NULL COMMENT 'Descripción del fichero.',
  STRCONTENTYPE   VARCHAR(255)  NOT NULL COMMENT 'Tipo de contenido del fichero.',
  NUMTAMANIO    	INT   	      NOT NULL COMMENT 'Tamaño del fichero.',
  DATCREACION		  DATETIME	    NOT NULL DEFAULT CURRENT_TIMESTAMP 'Fecha de creación del fichero.',
  FICHERO			    BLOB		      NOT NULL COMMENT 'Contenido del fichero.',
  PRIMARY KEY (NUMIDFICHERO)
) COMMENT 'Tabla que contiene los ficheros generados por las justificaciones.';
---------------------- ORACLE ------------------------
CREATE SEQUENCE TECNICOS_INV.JUST_FICHEROS_SQ;

CREATE TABLE TECNICOS_INV.TB_UC3M_INV_JUST_FICHEROS (
  NUMIDFICHERO    NUMBER(8)     NOT NULL,
  STRDESCRIPCION  VARCHAR2(50)  NOT NULL,
  STRCONTENTYPE   VARCHAR2(50)  NOT NULL,
  NUMTAMANIO      VARCHAR2(20)  NOT NULL,
  DATCREACION		  DATE    	    DEFAULT SYSDATE NOT NULL,
  FICHERO			    BLOB		      NOT NULL
);

COMMENT ON TABLE TECNICOS_INV.TB_UC3M_INV_JUST_FICHEROS IS 'Tabla que contiene los ficheros generados por las justificaciones.';
COMMENT ON COLUMN TECNICOS_INV.TB_UC3M_INV_JUST_FICHEROS.NUMIDFICHERO IS 'Identificador del fichero.';
COMMENT ON COLUMN TECNICOS_INV.TB_UC3M_INV_JUST_FICHEROS.STRDESCRIPCION IS 'Descripción del fichero.';
COMMENT ON COLUMN TECNICOS_INV.TB_UC3M_INV_JUST_FICHEROS.STRCONTENTYPE IS 'Tipo de contenido del fichero.';
COMMENT ON COLUMN TECNICOS_INV.TB_UC3M_INV_JUST_FICHEROS.NUMTAMANIO IS 'Tamaño del fichero.';
COMMENT ON COLUMN TECNICOS_INV.TB_UC3M_INV_JUST_FICHEROS.DATCREACION IS 'Fecha de creación del fichero.';
COMMENT ON COLUMN TECNICOS_INV.TB_UC3M_INV_JUST_FICHEROS.FICHERO IS 'Contenido del fichero.';

CREATE UNIQUE INDEX TECNICOS_INV.JUST_FICHEROS_PK_I ON TECNICOS_INV.TB_UC3M_INV_JUST_FICHEROS (NUMIDFICHERO);

ALTER TABLE TECNICOS_INV.TB_UC3M_INV_JUST_FICHEROS ADD (
  CONSTRAINT JUST_FICHEROS_PK
  PRIMARY KEY (NUMIDFICHERO)
  USING INDEX TECNICOS_INV.JUST_FICHEROS_PK_I
  ENABLE VALIDATE
);

CREATE OR REPLACE TRIGGER TG_JUST_FICHEROS_SQ
  BEFORE INSERT 
  ON TB_UC3M_INV_JUST_FICHEROS FOR EACH ROW
BEGIN
  IF :new.NUMIDFICHERO IS NULL THEN
    SELECT JUST_FICHEROS_SQ.nextval INTO :new.NUMIDFICHERO FROM DUAL;
  END IF;
END;
/
------------------------------------------------------
