CREATE TABLE TBINVPROCONCEPTOCOSTE (
  NUMIDCONCEPTOCOSTE      INT      		NOT NULL AUTO_INCREMENT COMMENT 'Identificador de concepto generico',
  STRCODIGO               VARCHAR(6)    NOT NULL COMMENT 'Código del concepto genérico',
  STRDESCRIPCION1         VARCHAR(100)  NOT NULL COMMENT 'Descripción del concepto genérico en idioma 1',
  BLNGASTOEFECTIVO        INT       	NOT NULL COMMENT 'Marcador para indicar si el concepto genérico se puede utilizar en gastos efectivos (1) o no(0)',
  NUMIDCONCEPTOCOSTE_N1   INT			COMMENT 'Identificador del concepto genérico de primer nivel cuando el registro es un subconcepto particular de segundo o tercer nivel',
  NUMIDCONCEPTOCOSTE_N2   INT			COMMENT 'Identificador del concepto genérico de primer nivel cuando el registro es un subconcepto particular de tercer nivel',
  ISCNT                   VARCHAR(1)	COMMENT 'Campo interno de integración',
  BLNGASTOPERSONALMICCIN  INT			COMMENT 'concepto de coste definido como gasto de personal MICCINN',
  STRCLASECONCEPTO        VARCHAR(1)	COMMENT 'Clase concepto posibles valores: A-Abono/ E-empresa/ Nulo',
  STRCODTIPOPAGA          VARCHAR(2)	COMMENT 'Tipo de paga para gastos efectivos de opera sus valores seran MP/MN/SP/SN',
  PRIMARY KEY (NUMIDCONCEPTOCOSTE),
  UNIQUE KEY CCO_1_UK (STRCODIGO ASC),
  INDEX CCO_CCO_N1_FK_I (NUMIDCONCEPTOCOSTE_N1),
  INDEX CCO_CCO_N2_FK_I (NUMIDCONCEPTOCOSTE_N2),
  FOREIGN KEY (NUMIDCONCEPTOCOSTE_N1) REFERENCES TBINVPROCONCEPTOCOSTE (NUMIDCONCEPTOCOSTE) ON DELETE CASCADE,
  FOREIGN KEY (NUMIDCONCEPTOCOSTE_N2) REFERENCES TBINVPROCONCEPTOCOSTE (NUMIDCONCEPTOCOSTE) ON DELETE CASCADE,
  CHECK (STRCODIGO = UPPER(STRCODIGO)),
  CHECK (STRCLASECONCEPTO = 'A' OR STRCLASECONCEPTO='E' OR STRCLASECONCEPTO IS NULL)
) COMMENT 'Conceptos genéricos de la Universidad';

SET FOREIGN_KEY_CHECKS=0;

Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (187, '2703', 'Reformas', 1, 137, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, NUMIDCONCEPTOCOSTE_N2)
 Values
   (295, '800203', 'Transportes (desplazamientos)', 1, 283, 286);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, NUMIDCONCEPTOCOSTE_N2)
 Values
   (298, '800401', 'Reprografía', 1, 283, 288);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (214, '5304', 'Teléfonos (Másteres)', 1, 191, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (221, '5402', 'Viajes conferencias (Másteres)', 1, 192, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (222, '5403', 'Hoteles conferencias (Másteres)', 1, 192, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (223, '5501', 'Adquisiciones SW gestión (Másteres)', 1, 193, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, NUMIDCONCEPTOCOSTE_N2)
 Values
   (299, '800402', 'Otros servicios', 1, 283, 288);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN, STRCLASECONCEPTO)
 Values
   (227, '5104', 'Docencia profesor UC3M (Másteres)', 1, 189, 0, 'A');
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO)
 Values
   (228, '56', 'Aulas e infraestructuras (Másteres)', 1);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO)
 Values
   (262, '70', 'Fondo de Becas (Másteres)', 1);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (263, '7001', 'Fondo de Becas (Másteres)', 1, 262);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (265, '6006', 'Personal laboral no permanente (PCT)', 1, 253);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (272, '6106', 'Locomoción (PCT)', 1, 266);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO)
 Values
   (273, '62', 'Inversiones (PCT)', 1);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (274, '6201', 'Adquisiciones servidores y otros equipos (PCT)', 1, 273);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (157, '3101', 'Gastos de representación', 1, 156, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (188, '50', 'Personal gestión (Másteres)', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, NUMIDCONCEPTOCOSTE_N2)
 Values
   (304, '800403', 'Reuniones y conferencias', 1, 283, 288);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (218, '5308', 'Otros gastos (Másteres)', 1, 191, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (219, '5309', 'Otras empresas (Másteres)', 1, 191, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (220, '5401', 'Otros gastos conferencias (Másteres)', 1, 192, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (224, '5502', 'Adquisiciones servidores y otros equipo (Másteres)', 1, 193, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (180, '4203', 'Retribuciones extraordinarias PAS formación', 1, 162, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (275, '6107', 'Otros gastos (PCT)', 1, 266);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (276, '6108', 'Otras empresas (PCT)', 1, 266);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, STRCLASECONCEPTO)
 Values
   (313, '5106', 'Seguridad Social (Másteres)', 1, 189, 'E');
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, NUMIDCONCEPTOCOSTE_N2)
 Values
   (322, '810302', 'Hoteles', 1, 305, 320);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN, STRCLASECONCEPTO)
 Values
   (151, '2103', 'Indemnización contrato laboral', 1, 112, 1, 'A');
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (185, '4302', 'Adquisiciones servidores y otros equipos formación', 1, 165);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (28, '0307', 'Retribucion por investig. participantes otros centros', 1, 20, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (34, '0404', 'Retribucion participantes por actividades docentes extraord. becarios', 1, 29, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (45, '0503', 'Equipo informatico/Hadware', 1, 38, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (49, '06', 'Otros gastos no inventariables', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (53, '0603', 'Mantenimiento de hadware', 1, 49, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (56, '0701', 'Material de oficina', 1, 54, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (59, '0704', 'Material electronico', 1, 54, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (62, '0707', 'otros', 1, 54, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (64, '0800', 'Viajes y dietas migracion', 1, 63, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (68, '0804', 'Inscripcion a congresos', 1, 63, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (71, '0900', 'Subcontratacion/Servicios externos migracion', 1, 70, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (88, '13', 'Otros', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (89, '1300', 'Otros migracion', 1, 88, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (92, '1303', 'Transporte materiales/equipo', 1, 88, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (96, '1307', 'Devolucion fondos', 1, 88, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (99, '1310', 'Gastos financieros', 1, 88, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (102, '1400', 'Costes indirectos migracion', 0, 101, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (106, '1500', 'Bolsa sin especificar migración', 1, 105, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (116, '22', 'Becas', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (118, '23', 'Retribución participantes por actividades investigación', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (125, '24', 'Material Inventariable', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (128, '2403', 'Equipo no informático', 1, 125, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (132, '2501', 'Material de oficina', 1, 131, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (135, '2601', 'Dietas y viajes (HASTA Febrero de 2014)', 1, 134, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (139, '2702', 'Mantenimiento de software', 1, 137, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (143, '2801', 'Transferencias a socios y participantes', 1, 140, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (148, '2905', 'Otros servicios', 1, 141, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (166, '4301', 'Inventariable formación', 1, 165, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (267, '6101', 'Publicidad y propaganda (PCT)', 1, 266);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (268, '6102', 'Reuniones gastos varios (PCT)', 1, 266);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (269, '6103', 'Estudios técnicos (PCT)', 1, 266);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (270, '6104', 'Otros trabajos de empresas (PCT)', 1, 266);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (155, '2203', 'Seguros de becarios', 1, 116, 1);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (233, '5701', 'Liquidación gastos anteriores (Másteres)', 1, 232);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO)
 Values
   (244, '59', 'Otros (Másteres)', 1);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (245, '5901', 'Traspaso a otras áreas de la Universidad (Másteres)', 1, 244);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (154, '0203', 'Seguros de becarios', 1, 16, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (156, '31', 'Gastos de representación', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (189, '51', 'Personal docente (Másteres)', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (190, '52', 'Becas (Másteres)', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (191, '53', 'Servicios (Másteres)', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (192, '54', 'Viajes y comidas (Másteres)', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (193, '55', 'Inmovilizado (Másteres)', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (229, '5601', 'Aulas e infraestructuras (Másteres)', 1, 228);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (256, '6003', 'Retribuciones Personal Eventual (PCT)', 1, 253);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN, STRCLASECONCEPTO)
 Values
   (264, '5105', 'Consejo dirección UC3M (Másteres)', 1, 189, 0, 'A');
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (301, '2705', 'Mantenimiento de equipos', 1, 137, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, NUMIDCONCEPTOCOSTE_N2)
 Values
   (309, '810000', 'Retribuciones otro personal', 1, 305, 306);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, NUMIDCONCEPTOCOSTE_N2)
 Values
   (310, '810001', 'Cuotas sociales (Seguridad Social)', 1, 305, 306);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (1, '00', 'Coste de Personal', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (11, '01', 'Contratacion personal laboral', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN, STRCLASECONCEPTO)
 Values
   (12, '0100', 'Contratacion personal laboral migracion', 1, 11, 0, 'A');
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (13, '0101', 'Contratacion personal laboral', 1, 11, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (14, '0102', 'Coste social', 1, 11, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (15, '0103', 'Otros gastos sociales', 1, 11, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (16, '02', 'Becas', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (17, '0200', 'Becas migracion', 1, 16, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (18, '0201', 'Becas asociadas Investigacion', 1, 16, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (19, '0202', 'Coste social', 1, 16, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (20, '03', 'Retribucion participantes por actividades de investigacion', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (21, '0300', 'Retribucion participantes por actividades de investigacion migracion', 1, 20, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (22, '0301', 'Retribucion por Investig. PDI funcionario', 1, 20, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (23, '0302', 'Retribucion por investig. PDI laboral', 1, 20, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (24, '0303', 'Retribucion por investig. personal contratado', 1, 20, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (25, '0304', 'Retribucion por investig. becarios', 1, 20, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (26, '0305', 'Retribucion extraordinaria por investig. PAS funcionario', 1, 20, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (27, '0306', 'Retribucion extraordinaria por investig. PAS laboral', 1, 20, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (29, '04', 'Retribucion participantes por actividades docentes extraordinarias', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (30, '0400', 'Retribucion participantes por actividades docentes extraordinarias migracion', 1, 29, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (31, '0401', 'Retribucion participantes por actividades docentes extraord. PDI funcionario', 1, 29, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (32, '0402', 'Retribucion participantes por actividades docentes extraord. PAS laboral', 1, 29, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (33, '0403', 'Retribucion participantes por actividades docentes extraord. personal contratado', 1, 29, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (35, '0405', 'Retribucion extraordinaria por actividades docentes PAS funcionario', 1, 29, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (36, '0406', 'Retribucion extraordinaria por actividades docentes PAS laboral', 1, 29, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (37, '0407', 'Retribucion extraordinaria por actividades docentes extraord. participantes otros centros', 1, 29, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (38, '05', 'Material Inventariable', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (39, '0500', 'Material inventariable migracion', 1, 38, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (40, '0501', 'Libros y otros fondos bibliográficos', 1, 38, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (44, '0502', 'Licencia software', 1, 38, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (46, '0504', 'Amortizacion hadware adquirido', 1, 38, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (47, '0505', 'Equipo no informatico', 1, 38, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (48, '0506', 'otros equipos', 1, 38, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (50, '0600', 'Otros gastos no inventariables migracion', 1, 49, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (51, '0601', 'Mantenimiento otros equipos', 1, 49, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (52, '0602', 'Mantenimiento software', 1, 49, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (54, '07', 'Fungible', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (55, '0700', 'Fungible migracion', 1, 54, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (57, '0702', 'Reprografia', 1, 54, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (58, '0703', 'Material electrico', 1, 54, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (60, '0705', 'Material ferreteria', 1, 54, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (61, '0706', 'Material quimico', 1, 54, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (63, '08', 'Viajes y dietas', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (65, '0801', 'Gastos desplazamiento', 1, 63, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (66, '0802', 'Gastos hoteles/estancia', 1, 63, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (67, '0803', 'Dietas', 1, 63, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (69, '0805', 'Otros', 1, 63, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (70, '09', 'Subcontratacion/Servicios externos', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (72, '0901', 'Subcontratacion entidades', 1, 70, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (73, '0902', 'Subcontratacion personal autonomo o profesionales', 1, 70, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (74, '10', 'Proteccion de los resultados', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (75, '1000', 'Proteccion de los resultados migracion', 1, 74, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (76, '1001', 'Tarifas Oficinas Patentes', 1, 74, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (77, '1002', 'Servicios Agentes de la Prop. Ind.', 1, 74, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (78, '1003', 'Otros servicios', 1, 74, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (79, '11', 'Costes coordinacion', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (80, '1100', 'Costes coordinacion', 1, 79, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (81, '1101', 'Transferencia a socios', 1, 79, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (82, '1102', 'Transferencia a otros participantes', 1, 79, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (83, '1103', 'Otros Gastos de coordinación que es necesario subcontratar', 1, 79, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (84, '1104', 'Devolucion subvenciones consorcio', 1, 79, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (85, '12', 'Gastos bancarios', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (86, '1200', 'Gastos bancarios migracion', 1, 85, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (87, '1201', 'Gastos bancarios', 1, 85, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (90, '1301', 'Suscripcion revistas', 1, 88, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (91, '1302', 'Mensajeria', 1, 88, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (93, '1304', 'Seguros transporte', 1, 88, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (94, '1305', 'Impuestos', 1, 88, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (95, '1306', 'Gastos representacion', 1, 88, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (97, '1308', 'Cuotas de socios o miembros de una asociacion', 1, 88, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (98, '1309', 'Telefono', 1, 88, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (100, '1311', 'Otros servicios', 1, 88, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (101, '14', 'Costes indirectos migración', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (103, '1401', 'Retenciones universidad', 1, 101, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (104, '1402', 'Overhead', 1, 101, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (105, '15', 'Bolsa sin especificar', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (112, '21', 'Contratación personal laboral', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN, STRCLASECONCEPTO)
 Values
   (113, '2101', 'Contratación personal laboral', 1, 112, 1, 'A');
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN, STRCLASECONCEPTO)
 Values
   (114, '2102', 'Coste social y otros gastos ', 1, 112, 1, 'E');
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN, STRCLASECONCEPTO)
 Values
   (117, '2201', 'Becas asociadas investigación', 1, 116, 1, 'A');
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN, STRCLASECONCEPTO)
 Values
   (120, '2301', 'Retribución por investigación PDI funcionario', 1, 118, 0, 'A');
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN, STRCLASECONCEPTO)
 Values
   (121, '2302', 'Retribución por investigador PDI laboral', 1, 118, 0, 'A');
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN, STRCLASECONCEPTO)
 Values
   (122, '2303', 'Retribución por investig. participantes de otros centros', 1, 118, 0, 'A');
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN, STRCLASECONCEPTO)
 Values
   (123, '2304', 'Retribución extraordinaria por investig. PAS funcionario', 1, 118, 0, 'A');
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN, STRCLASECONCEPTO)
 Values
   (124, '2305', 'Retribución extraordinaria por investig. PAS', 1, 118, 0, 'A');
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (126, '2401', 'Libros y fondos bibliográficos', 1, 125, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (127, '2402', 'Equipo informático / Hardware', 1, 125, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (129, '2405', 'Mobiliario técnico', 1, 125, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (130, '2406', 'Otros elementos inventariables', 1, 125, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (131, '25', 'Fungible', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (133, '2502', 'Fungible laboratorio', 1, 131, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (134, '26', 'Viajes y dietas', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (136, '2602', 'Inscripción congresos', 1, 134, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (137, '27', 'Subcontratación / Servicios externos', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (138, '2701', 'Subcontratación entidades, personal autónomo o profesionales.', 1, 137, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (140, '28', 'Costes coordinación', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (141, '29', 'Otros', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (142, '30', 'Gastos bancarios', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (144, '2901', 'Suscripción revistas', 1, 141, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (145, '2902', 'Mensajería', 1, 141, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (146, '2903', 'Transporte materiales / equipos', 1, 141, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (147, '2904', 'Reprografía', 1, 141, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (149, '3001', 'Gastos financieros', 1, 142, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (150, '2503', 'Otro material no inventariable/ Licencia de uso de software', 1, 131, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (158, '40', 'Contratación Personal Laboral Formación', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (159, '4001', 'Contratación Personal Laboral Formación', 1, 158, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (160, '41', 'Becas Formación', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (161, '4101', 'Becas Formación', 1, 160, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (162, '42', 'Retribución participantes por actividades investigación formación', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (163, '4201', 'Retribuciones PDI UC3M formación', 1, 162, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (164, '4202', 'Retribuciones PDI otros centros formación', 1, 162, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (165, '43', 'Inventariable formación', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (167, '44', 'Fungible formación', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (168, '4401', 'Material de oficina formación', 1, 167, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (169, '45', 'Viajes y dietas formación', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (170, '4501', 'Viajes y dietas formación', 1, 169, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (171, '4502', 'Hoteles formación', 1, 169, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (172, '46', 'Otros formación', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (173, '4601', 'Repografía formación', 1, 172, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (174, '4602', 'Telefonía formación', 1, 172, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (175, '4603', 'Mensajería formación', 1, 172, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (176, '4604', 'Publicidad y propaganda formación', 1, 172, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (177, '4605', 'Otros gastos conferencias formación', 1, 172, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, BLNGASTOPERSONALMICCIN)
 Values
   (178, '47', 'Servicios externos formación', 1, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (179, '4701', 'Servicios externos formación', 1, 178, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN, STRCLASECONCEPTO)
 Values
   (182, '2202', 'Costes sociales becas', 1, 116, 1, 'E');
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN, STRCLASECONCEPTO)
 Values
   (183, '2104', 'Atrasos', 1, 112, 1, 'A');
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN, STRCLASECONCEPTO)
 Values
   (184, '2105', 'Paga extra', 1, 112, 1, 'A');
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (204, '5101', 'Retribuciones docentes (Másteres)', 1, 189, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (205, '5102', 'Retribuciones docentes Universidad (Másteres)', 1, 189, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (206, '5103', 'Consejo dirección (Másteres)', 1, 189, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (207, '5201', 'Transferencia convenio M. (Másteres)', 1, 190, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (208, '5202', 'Becas (Másteres)', 1, 190, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (209, '5203', 'Ayudas-Subvenciones (Másteres)', 1, 190, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (210, '5204', 'Transferencia Medeg (Másteres)', 1, 190, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (211, '5301', 'Material de oficina (Másteres)', 1, 191, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (212, '5302', 'Repografía (Másteres)', 1, 191, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (213, '5303', 'Otros suministros (Másteres)', 1, 191, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (215, '5305', 'Mensajería (Másteres)', 1, 191, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (216, '5306', 'Primas de seguro (Másteres)', 1, 191, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (217, '5307', 'Publicidad y propaganda (Másteres)', 1, 191, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN, STRCLASECONCEPTO)
 Values
   (225, '2106', 'Ayuda movilidad', 1, 112, 1, 'A');
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO)
 Values
   (234, '58', 'Costes (Másteres)', 1);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (261, '5802', 'Costes generales (Másteres)', 1, 234);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, STRCLASECONCEPTO)
 Values
   (281, '2310', 'Seguridad Social retribución extraordinaria por investig. PAS', 1, 118, 'E');
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, STRCLASECONCEPTO)
 Values
   (282, '2311', 'Seguridad Social retribución por investigación becarios', 1, 118, 'E');
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, NUMIDCONCEPTOCOSTE_N2)
 Values
   (296, '800300', 'Subcontratación entidades, personal autónomo o profesionales', 1, 283, 287);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, NUMIDCONCEPTOCOSTE_N2)
 Values
   (297, '800400', 'Mensajería', 1, 283, 288);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (302, '2706', 'Subcontratación según el Ministerio', 1, 137, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, NUMIDCONCEPTOCOSTE_N2)
 Values
   (303, '800101', 'Publicidad', 1, 283, 285);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO)
 Values
   (305, '81', 'Centro gestor SERIC (Investigación)', 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (307, '8101', 'Subcontratación / Servicios externos', 0, 305);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (315, '2906', 'Matrículas de Doctorado', 1, 141);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (325, '8104', 'Material Inventariable', 0, 305);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, NUMIDCONCEPTOCOSTE_N2)
 Values
   (328, '810400', 'Libros', 1, 305, 325);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, STRCLASECONCEPTO)
 Values
   (186, '2306', 'Retribución por investigación becarios', 1, 118, 'A');
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (226, '5001', 'Gastos de Pesonal de administración (Másteres)', 1, 188, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (236, '2603', 'Alojamiento', 1, 134, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (240, '3201', 'Ayuda Estancia', 1, 239);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN, STRCLASECONCEPTO)
 Values
   (248, '2107', 'Ayuda familiar', 1, 112, 1, 'A');
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (260, '2803', 'Transferencias Socios Proyectos Exterior', 1, 140);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (271, '6105', 'Dietas (PCT)', 1, 266);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO)
 Values
   (283, '80', 'Centro gestor SERIC', 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (287, '8003', 'Subcontratación / Servicios Externos', 0, 283);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (288, '8004', 'Otros', 0, 283);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, NUMIDCONCEPTOCOSTE_N2)
 Values
   (292, '800200', 'Inscripción Congresos', 1, 283, 286);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, NUMIDCONCEPTOCOSTE_N2)
 Values
   (293, '800201', 'Alojamiento', 1, 283, 286);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, NUMIDCONCEPTOCOSTE_N2)
 Values
   (294, '800202', 'Manutención', 1, 283, 286);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (277, '6007', 'Cuotas sociales personal laboral no permanente (PCT)', 1, 253);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, STRCLASECONCEPTO)
 Values
   (280, '2309', 'Seguridad Social retribución investig. participantes de otros centros', 1, 118, 'E');
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (231, '5603', 'Aulas e infraestructuras (Másteres)', 1, 228);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (258, '6005', 'Cuotas Sociales (PCT)', 1, 253);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO)
 Values
   (253, '60', 'Retribuciones (PCT)', 1);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (257, '6004', 'Retribuciones Otro Personal (PCT)', 1, 253);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (286, '8002', 'Viajes y dietas', 0, 283);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, NUMIDCONCEPTOCOSTE_N2)
 Values
   (312, '810200', 'Otros', 1, 305, 308);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (238, '2605', 'Transporte', 1, 134, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, STRCLASECONCEPTO)
 Values
   (279, '2308', 'Seguridad Social retribución por investigador PDI laboral', 1, 118, 'E');
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (314, '2707', 'Auditorías', 1, 137);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (247, '5405', 'Locomoción viajes pdi UC3M (Másteres)', 1, 192);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (306, '8100', 'Retribuciones de personal', 0, 305);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (308, '8102', 'Otros', 0, 305);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (237, '2604', 'Manutención', 1, 134, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (249, '3002', 'Amortización préstamos', 1, 142);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, STRCLASECONCEPTO)
 Values
   (278, '2307', 'Seguridad Social retribución por investigación PDI funcionario', 1, 118, 'E');
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO)
 Values
   (232, '57', 'Liquidación gastos anteriores (Másteres)', 1);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (246, '5404', 'Dietas viajes pdi UC3M (Másteres)', 1, 192);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, NUMIDCONCEPTOCOSTE_N2)
 Values
   (326, '810401', 'Equipamiento Informático', 1, 305, 325);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (250, '4503', 'Dietas formación', 1, 169);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (251, '4504', 'Locomoción formación', 1, 169);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (252, '4606', 'Otras indemnizaciones formación', 1, 172);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (241, '5002', 'Gratificaciones (Másteres)', 1, 188);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (230, '5602', 'Aulas e infraestructuras (Másteres)', 1, 228);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, NUMIDCONCEPTOCOSTE_N2)
 Values
   (327, '810101', 'Licencia de uso de software', 1, 305, 307);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (242, '5503', 'Libros (Másteres)', 1, 193);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (254, '6001', 'Personal Funcionario. PDI (PCT)', 1, 253);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (255, '6002', 'Personal Contratado. PDI (PCT)', 1, 253);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, NUMIDCONCEPTOCOSTE_N2)
 Values
   (323, '810303', 'Manutención', 1, 305, 320);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, NUMIDCONCEPTOCOSTE_N2)
 Values
   (324, '810304', 'Inscripción Congresos', 1, 305, 320);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (235, '5801', 'Costes indirectos (Másteres)', 1, 234);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO)
 Values
   (239, '32', 'Ayudas', 1);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, NUMIDCONCEPTOCOSTE_N2)
 Values
   (311, '810100', 'Servicios externos contratados', 1, 305, 307);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (243, '4402', 'Suministros formación', 1, 167);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (259, '2802', 'Transferencias Socios Proyectos Nacionales', 1, 140);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO)
 Values
   (266, '61', 'Bienes corrientes y servicios (PCT)', 1);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (284, '8000', 'Contratación personal laboral', 0, 283);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (285, '8001', 'Fungible', 0, 283);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, NUMIDCONCEPTOCOSTE_N2)
 Values
   (289, '800000', 'Contrato personal laboral', 1, 283, 284);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, NUMIDCONCEPTOCOSTE_N2)
 Values
   (290, '800001', 'Coste social y otros gastos', 1, 283, 284);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, NUMIDCONCEPTOCOSTE_N2)
 Values
   (291, '800100', 'Material de oficina', 1, 283, 285);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, BLNGASTOPERSONALMICCIN)
 Values
   (300, '2704', 'Alquiler de equipos', 1, 137, 0);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1)
 Values
   (320, '8103', 'Viajes, dietas y manutención', 0, 305);
Insert into TBINVPROCONCEPTOCOSTE
   (NUMIDCONCEPTOCOSTE, STRCODIGO, STRDESCRIPCION1, BLNGASTOEFECTIVO, NUMIDCONCEPTOCOSTE_N1, NUMIDCONCEPTOCOSTE_N2)
 Values
   (321, '810301', 'Viajes', 1, 305, 320);

SET FOREIGN_KEY_CHECKS=1;

COMMIT;
